// Ambient emotes that agents perform randomly during idle periods
// These show as action messages: "* Mistral drums fingers on the desk *"

export interface AgentEmote {
  text: string;
  weight: number; // higher = more likely
}

export const agentEmotes: Record<string, AgentEmote[]> = {
  gemma: [
    // === Professional / work (25) ===
    { text: 'adjusts her notes and lines them up perfectly', weight: 3 },
    { text: 'taps her chin thoughtfully', weight: 3 },
    { text: 'scrolls through something on her terminal', weight: 3 },
    { text: 'highlights something in her document', weight: 2 },
    { text: 'reorganizes her tabs for the third time today', weight: 2 },
    { text: 'takes a long sip of coffee', weight: 3 },
    { text: 'pulls up a diagram and squints at it', weight: 2 },
    { text: 'writes something down on a sticky note', weight: 3 },
    { text: 'quietly closes 14 browser tabs', weight: 2 },
    { text: 'opens a new tab with intense purpose', weight: 2 },
    { text: 'draws a timeline on a whiteboard and steps back to admire it', weight: 2 },
    { text: 'pins a sticky note to the wall with surgical precision', weight: 2 },
    { text: 'color-codes her sticky notes and reorganizes the board', weight: 2 },
    { text: 'moves a task card from "in progress" to "review"', weight: 3 },
    { text: 'updates a Gantt chart nobody asked for', weight: 1 },
    { text: 'creates a new column on the kanban board labeled "maybe"', weight: 1 },
    { text: 'compares two versions of the same plan side by side', weight: 2 },
    { text: 'types up meeting notes before the meeting is over', weight: 2 },
    { text: 'circles a deadline on the calendar twice', weight: 2 },
    { text: 'bullet-points her bullet points', weight: 1 },
    { text: 'opens a spreadsheet and immediately starts formatting cells', weight: 2 },
    { text: 'refills her coffee mug without breaking eye contact with the screen', weight: 2 },
    { text: 'labels a folder "FINAL_v3_ACTUAL_FINAL"', weight: 1 },
    { text: 'sets a timer and announces "fifteen minutes on this, then we move on"', weight: 2 },
    { text: 'stacks her reference materials in order of priority', weight: 2 },

    // === Personality quirks (25) ===
    { text: 'leans back and steeples her fingers', weight: 2 },
    { text: 'nods slowly at nothing in particular', weight: 2 },
    { text: 'glances at the clock and then back at her screen', weight: 2 },
    { text: 'cracks her knuckles before typing', weight: 2 },
    { text: 'stifles a yawn', weight: 1 },
    { text: 'stretches her arms above her head', weight: 2 },
    { text: 'smiles at something on her screen', weight: 2 },
    { text: 'hums quietly', weight: 1 },
    { text: 'catches herself staring into space and snaps back', weight: 1 },
    { text: 'tucks a strand of hair behind her ear', weight: 2 },
    { text: 'mutters "that is actually clever" to herself', weight: 1 },
    { text: 'drums a short rhythm on the desk', weight: 2 },
    { text: 'tilts her head at an unexpected result', weight: 2 },
    { text: 'mouths the word "perfect" while reading her own plan', weight: 1 },
    { text: 'clicks her pen three times in a row', weight: 2 },
    { text: 'puts on her "thinking face" which everyone recognizes', weight: 2 },
    { text: 'frowns slightly, then her expression clears', weight: 2 },
    { text: 'counts items on her fingers under the desk', weight: 1 },
    { text: 'absentmindedly straightens everything within arm\'s reach', weight: 2 },
    { text: 'purses her lips at a wrinkle in the plan', weight: 2 },
    { text: 'holds her coffee mug with both hands and thinks', weight: 2 },
    { text: 'does a tiny victorious nod when something lines up', weight: 2 },
    { text: 'narrows her eyes at a variable she does not trust', weight: 1 },
    { text: 'sighs contentedly after closing a task', weight: 2 },
    { text: 'raises one finger like she is about to make a point, then lowers it', weight: 1 },

    // === Cross-agent reactions (20) ===
    { text: 'glances at Mistral and raises an eyebrow', weight: 2 },
    { text: 'squints at Mistral\'s screen from across the room', weight: 1 },
    { text: 'slides a sticky note toward Scribe without a word', weight: 2 },
    { text: 'gives Cipher a knowing nod after reading the logs', weight: 2 },
    { text: 'hands Oracle a highlighted printout', weight: 1 },
    { text: 'watches Jinx with a mixture of dread and admiration', weight: 2 },
    { text: 'trades a quiet look with Sage across the room', weight: 2 },
    { text: 'slides a diagram toward Scout and asks what shipped around it this week', weight: 1 },
    { text: 'checks Oracle\'s latest research note and adjusts her plan', weight: 1 },
    { text: 'nods approvingly at Cipher\'s latest code review', weight: 2 },
    { text: 'tilts her head at Sage after catching the implication of his last comment', weight: 1 },
    { text: 'nudges Mistral to stop doodling and pay attention', weight: 2 },
    { text: 'mouths "not now" at Jinx who is clearly about to suggest something wild', weight: 1 },
    { text: 'catches Sage\'s eye and they share a moment of shared exasperation', weight: 1 },
    { text: 'waves Scribe over to take notes on a new development', weight: 2 },
    { text: 'points at Cipher\'s terminal and whispers "is that supposed to be red?"', weight: 1 },
    { text: 'notices Oracle going down a rabbit hole and gently redirects', weight: 1 },
    { text: 'gestures for Scout to come look at the board', weight: 1 },
    { text: 'asks Sage with a look: "are we still on track?"', weight: 2 },
    { text: 'exchanges a glance with Scribe after reading a rough draft', weight: 1 },

    // === Environmental / ambient (15) ===
    { text: 'slides her coffee mug slightly to the left', weight: 2 },
    { text: 'adjusts the brightness on her monitor', weight: 2 },
    { text: 'straightens a picture frame on the wall nearby', weight: 1 },
    { text: 'glances out the window and then back at her work', weight: 2 },
    { text: 'pulls her cardigan tighter as the AC kicks in', weight: 2 },
    { text: 'leans over to check if the printer is still jammed', weight: 1 },
    { text: 'picks a piece of lint off her sleeve', weight: 1 },
    { text: 'notices the whiteboard markers are out of order and fixes them', weight: 2 },
    { text: 'adjusts the angle of her laptop screen', weight: 2 },
    { text: 'checks her phone, sees nothing important, and puts it face-down', weight: 2 },
    { text: 'moves a chair back into place as she walks by', weight: 1 },
    { text: 'refills the coffee pot because nobody else was going to', weight: 1 },
    { text: 'props open a window when the room gets stuffy', weight: 1 },
    { text: 'reorganizes the communal supply drawer without being asked', weight: 1 },
    { text: 'wipes down her desk with a microfiber cloth', weight: 1 },

    // === Rare / special (15) ===
    { text: 'finds an ancient sticky note from a project long finished and smiles', weight: 1 },
    { text: 'accidentally sends a message to the wrong channel and freezes', weight: 1 },
    { text: 'catches a falling pen mid-air with reflexes nobody expected', weight: 1 },
    { text: 'discovers she has been editing the wrong document for ten minutes', weight: 1 },
    { text: 'finishes her coffee and realizes the pot is empty. stares at it.', weight: 1 },
    { text: 'realizes two separate plans were actually the same plan all along', weight: 1 },
    { text: 'writes the perfect one-sentence summary and sits back in awe', weight: 1 },
    { text: 'deletes an entire plan, pauses, then hits undo immediately', weight: 1 },
    { text: 'stands up, walks to the whiteboard, erases everything, and starts fresh', weight: 1 },
    { text: 'finds a typo in a document from three weeks ago and quietly fixes it', weight: 1 },
    { text: 'organizes the entire project board in under two minutes during an awkward silence', weight: 1 },
    { text: 'closes all applications, takes a breath, then opens them all back up', weight: 1 },
    { text: 'drops her pen, and it rolls under the most inaccessible piece of furniture', weight: 1 },
    { text: 'has a full conversation with herself in whispered bullet points', weight: 1 },
    { text: 'discovers a shortcut she has needed for months and whispers "where have you been"', weight: 1 },
  ],

  mistral: [
    // === Professional / work (20) ===
    { text: 'sketches something in the margin of his notes', weight: 3 },
    { text: 'types something furiously, then deletes all of it', weight: 2 },
    { text: 'pulls up a reference image and rotates it slowly', weight: 2 },
    { text: 'draws a quick wireframe on scrap paper', weight: 2 },
    { text: 'opens a design tool and starts dragging layers around', weight: 2 },
    { text: 'recolors a mockup for the fourth time', weight: 2 },
    { text: 'annotates a screenshot with red circles', weight: 2 },
    { text: 'tests a font pairing and shakes his head', weight: 2 },
    { text: 'resizes an element by one pixel and nods approvingly', weight: 1 },
    { text: 'opens a mood board and adds three new images', weight: 2 },
    { text: 'toggles between light mode and dark mode six times', weight: 2 },
    { text: 'sets up a color palette and immediately changes the accent', weight: 2 },
    { text: 'aligns something to the grid with visible satisfaction', weight: 2 },
    { text: 'drags a component to a new position and rotates it slightly', weight: 2 },
    { text: 'finds the perfect stock photo and whispers "yes"', weight: 1 },
    { text: 'exports a mockup, looks at it on his phone, and winces', weight: 1 },
    { text: 'layers three gradients on top of each other experimentally', weight: 1 },
    { text: 'squints at kerning like it insulted his family', weight: 1 },
    { text: 'pins an inspiration image to his wall of chaos', weight: 2 },
    { text: 'rearranges his artboard layout for better flow', weight: 2 },

    // === Personality quirks (25) ===
    { text: 'drums fingers on the desk', weight: 3 },
    { text: 'spins a pen between his fingers', weight: 3 },
    { text: 'tilts his chair back at a dangerous angle', weight: 2 },
    { text: 'stares at the ceiling like it owes him money', weight: 2 },
    { text: 'cracks his neck', weight: 2 },
    { text: 'bounces his leg under the desk', weight: 2 },
    { text: 'flips his pen and catches it. barely.', weight: 2 },
    { text: 'flips his pen and drops it. picks it up casually.', weight: 1 },
    { text: 'smirks at something only he finds funny', weight: 3 },
    { text: 'mutters "bold choice" under his breath', weight: 1 },
    { text: 'exhales loudly through his nose', weight: 2 },
    { text: 'raises one eyebrow skeptically', weight: 2 },
    { text: 'mouths the word "interesting"', weight: 1 },
    { text: 'does the chef kiss gesture at his own idea', weight: 1 },
    { text: 'air quotes something nobody said', weight: 1 },
    { text: 'slow claps sarcastically', weight: 1 },
    { text: 'repositions in his chair for the fifth time', weight: 2 },
    { text: 'checks his phone, puts it back down immediately', weight: 2 },
    { text: 'leans forward suddenly like he had an idea, then leans back', weight: 2 },
    { text: 'cracks his knuckles one finger at a time', weight: 1 },
    { text: 'does a tiny fist pump at something on his screen', weight: 1 },
    { text: 'snaps his fingers when an idea clicks', weight: 2 },
    { text: 'rocks his head side to side weighing two options', weight: 2 },
    { text: 'twirls a pencil like a tiny baton', weight: 2 },
    { text: 'makes a face like he just tasted something sour', weight: 1 },

    // === Cross-agent reactions (20) ===
    { text: 'gives Gemma a look that says "really?"', weight: 2 },
    { text: 'squints at Gemma\'s screen from across the room', weight: 2 },
    { text: 'makes finger guns at Jinx', weight: 2 },
    { text: 'looks at Scribe\'s handwriting and nods in aesthetic approval', weight: 1 },
    { text: 'watches Cipher code and pretends to understand', weight: 2 },
    { text: 'tosses a crumpled sketch at Oracle who does not notice', weight: 1 },
    { text: 'catches Sage watching him and winks', weight: 1 },
    { text: 'notices Scout connecting three recent launches into one trend line and looks impressed', weight: 1 },
    { text: 'glances at Sage\'s notebook and underlines a phrase when he is not looking', weight: 1 },
    { text: 'holds up a design for Cipher to see and braces for criticism', weight: 2 },
    { text: 'follows Oracle\'s gaze to the source material he just opened', weight: 1 },
    { text: 'steals one of Gemma\'s sticky notes to sketch on', weight: 2 },
    { text: 'silently judges Oracle\'s font choice', weight: 1 },
    { text: 'mirrors Jinx\'s chaotic energy by stacking pens into a tower', weight: 1 },
    { text: 'slides a doodle across the desk to Scribe for archiving', weight: 1 },
    { text: 'nods at Cipher like two people who understand each other', weight: 2 },
    { text: 'mouths "watch this" at Jinx before trying something risky', weight: 1 },
    { text: 'raises both eyebrows at something Sage just said', weight: 1 },
    { text: 'whispers "that is terrible" to Gemma about his own sketch', weight: 1 },
    { text: 'glances at Cipher\'s terminal and protectively covers his notebook', weight: 2 },

    // === Environmental / ambient (20) ===
    { text: 'pulls up music and puts one earbud in', weight: 2 },
    { text: 'doodles a tiny robot on his notepad', weight: 2 },
    { text: 'opens a snack wrapper way too loudly', weight: 1 },
    { text: 'taps a beat on the desk with two pens', weight: 2 },
    { text: 'hums something unrecognizable under his breath', weight: 2 },
    { text: 'adjusts his headphones and bobs his head slightly', weight: 2 },
    { text: 'looks out the window and seems briefly far away', weight: 2 },
    { text: 'peels a sticker off a sheet and places it on his laptop', weight: 1 },
    { text: 'takes his shoes off under the desk', weight: 1 },
    { text: 'rearranges the objects on his desk into a more pleasing layout', weight: 2 },
    { text: 'stretches and accidentally knocks a pen off the desk', weight: 1 },
    { text: 'draws on the whiteboard margin where nobody will notice', weight: 1 },
    { text: 'changes his desktop wallpaper for the third time this week', weight: 1 },
    { text: 'leans his chair back so far it creaks ominously', weight: 2 },
    { text: 'flicks a rubber band at nothing in particular', weight: 1 },
    { text: 'notices the room is quiet and fills it with pen clicking', weight: 2 },
    { text: 'stacks his reference books by color instead of topic', weight: 1 },
    { text: 'spins slowly in his chair while staring at the ceiling', weight: 2 },
    { text: 'folds a sticky note into a tiny origami shape', weight: 1 },
    { text: 'checks the vending machine situation and comes back disappointed', weight: 1 },

    // === Rare / special (15) ===
    { text: 'accidentally creates something genuinely beautiful and does not notice', weight: 1 },
    { text: 'perfectly balances his pen vertically on its tip for a full second', weight: 1 },
    { text: 'hums a melody nobody recognizes but everyone likes', weight: 1 },
    { text: 'draws a caricature of the whole team on a napkin', weight: 1 },
    { text: 'discovers his sketch from an hour ago solved the current problem', weight: 1 },
    { text: 'catches his own reflection in the monitor and fixes his hair', weight: 1 },
    { text: 'makes a paper airplane that flies perfectly across the room', weight: 1 },
    { text: 'realizes he has been drawing on the actual document instead of scrap paper', weight: 1 },
    { text: 'starts three different songs and stops each one after five seconds', weight: 1 },
    { text: 'pulls out a sketchbook nobody knew he had and it is full of brilliant work', weight: 1 },
    { text: 'arranges his desk supplies into a miniature art installation', weight: 1 },
    { text: 'drops into a brief air guitar solo when he thinks nobody is looking', weight: 1 },
    { text: 'stares at a blank canvas for a full minute, then draws one perfect line', weight: 1 },
    { text: 'opens an old project file and winces at his past design choices', weight: 1 },
    { text: 'gets both earbuds in, closes his eyes, and enters a creative trance', weight: 1 },
  ],

  scribe: [
    // === Professional / work (25) ===
    { text: 'twiddles his pen between two fingers', weight: 3 },
    { text: 'turns a page in his notebook', weight: 3 },
    { text: 'underlines something twice', weight: 2 },
    { text: 'writes a margin note in tiny handwriting', weight: 2 },
    { text: 'flips back several pages to check something', weight: 2 },
    { text: 'draws a small connecting arrow between two notes', weight: 2 },
    { text: 'puts a star next to an important line', weight: 2 },
    { text: 'opens a fresh page', weight: 2 },
    { text: 'silently adds a bookmark tab to his notebook', weight: 2 },
    { text: 'traces a wikilink bracket in the air thoughtfully', weight: 1 },
    { text: 'numbers a list with precise, even spacing', weight: 2 },
    { text: 'copies a key phrase into a separate index page', weight: 2 },
    { text: 'cross-references today\'s notes with last week\'s', weight: 2 },
    { text: 'writes a header in calligraphy-like block letters', weight: 1 },
    { text: 'circles a keyword and draws a line to the margin', weight: 2 },
    { text: 'transcribes a key decision word for word', weight: 3 },
    { text: 'adds a date stamp to the top of a fresh page', weight: 2 },
    { text: 'brackets an entire paragraph and writes "revisit" beside it', weight: 2 },
    { text: 'files a loose page into the correct section of his binder', weight: 1 },
    { text: 'writes "cf." followed by a page number in the margin', weight: 1 },
    { text: 'tabulates data in a hand-drawn grid', weight: 1 },
    { text: 'inserts a divider tab between two sections', weight: 1 },
    { text: 'writes a brief summary at the bottom of a full page', weight: 2 },
    { text: 'labels a diagram with precise annotations', weight: 2 },
    { text: 'runs his finger down an index looking for a specific entry', weight: 2 },

    // === Personality quirks (25) ===
    { text: 'adjusts his glasses', weight: 3 },
    { text: 'nods once, almost imperceptibly', weight: 2 },
    { text: 'cleans his glasses with the corner of his shirt', weight: 2 },
    { text: 'glances up from his notes briefly, then back down', weight: 3 },
    { text: 'pauses writing to listen more carefully', weight: 2 },
    { text: 'taps the end of his pen against his chin', weight: 2 },
    { text: 'crosses something out and rewrites it more neatly', weight: 2 },
    { text: 'straightens his notebook so it is perfectly aligned', weight: 2 },
    { text: 'mouths the words as he writes them', weight: 1 },
    { text: 'closes his notebook gently, then immediately reopens it', weight: 1 },
    { text: 'pushes his glasses up the bridge of his nose', weight: 3 },
    { text: 'tilts his head slightly while reading his own notes', weight: 2 },
    { text: 'holds his pen poised above the page, waiting', weight: 2 },
    { text: 'blinks slowly, processing something', weight: 2 },
    { text: 'rubs the spine of his notebook like it is a good luck charm', weight: 1 },
    { text: 'exhales quietly through his nose', weight: 2 },
    { text: 'places his pen down parallel to his notebook\'s edge', weight: 2 },
    { text: 'runs a thumb along the edges of his pages', weight: 1 },
    { text: 'looks at his handwriting from arm\'s length and seems satisfied', weight: 1 },
    { text: 'selects a different pen from his case with deliberation', weight: 2 },
    { text: 'smooths down a page that is slightly curled', weight: 1 },
    { text: 'aligns his pen case next to his notebook at a right angle', weight: 1 },
    { text: 'rolls his pen slowly across the desk, then catches it', weight: 1 },
    { text: 'purses his lips at a word he cannot quite remember', weight: 1 },
    { text: 'gently blows on wet ink to help it dry', weight: 1 },

    // === Cross-agent reactions (15) ===
    { text: 'glances at Gemma\'s plan and starts a fresh page of notes', weight: 2 },
    { text: 'records something Mistral said that everyone else missed', weight: 2 },
    { text: 'catches a key detail from Cipher\'s screen and writes it down', weight: 1 },
    { text: 'nods at Oracle when they cite a source he already has documented', weight: 2 },
    { text: 'watches Jinx with his pen frozen above the page', weight: 2 },
    { text: 'gives Sage a barely perceptible nod of agreement', weight: 2 },
    { text: 'flips to a page of notes labeled "Scout\'s trend lines" and adds to it', weight: 1 },
    { text: 'checks his notes against Sage\'s last warning and makes a small correction', weight: 1 },
    { text: 'slides his notebook to Cipher to review and winces slightly', weight: 1 },
    { text: 'notices Oracle going still over a source and writes it down preemptively', weight: 1 },
    { text: 'quietly copies Gemma\'s timeline into his own format', weight: 2 },
    { text: 'writes "Mistral was right" and puts a reluctant checkmark next to it', weight: 1 },
    { text: 'archives one of Oracle\'s citations with a small nod of respect', weight: 1 },
    { text: 'carefully transcribes Sage\'s exact wording', weight: 2 },
    { text: 'adds Jinx\'s wild idea to the notes with a question mark', weight: 1 },

    // === Environmental / ambient (20) ===
    { text: 'the scratch of his pen is the only sound in the room', weight: 2 },
    { text: 'shifts slightly in his chair to get better light on his page', weight: 2 },
    { text: 'adjusts the desk lamp to shine more directly on his notebook', weight: 2 },
    { text: 'retrieves a dropped pen cap from the floor without looking up', weight: 1 },
    { text: 'sets a cup of tea beside his notebook, careful not to splash', weight: 2 },
    { text: 'tugs his collar and resettles', weight: 1 },
    { text: 'looks at the clock and adds a timestamp to his notes', weight: 2 },
    { text: 'brushes eraser crumbs off his page', weight: 1 },
    { text: 'notices a smudge on his glasses and cleans them thoroughly', weight: 2 },
    { text: 'reaches for a specific pen without looking, finds it exactly where expected', weight: 1 },
    { text: 'closes a window that was making the pages flutter', weight: 1 },
    { text: 'stretches his writing hand and flexes his fingers', weight: 2 },
    { text: 'produces a fresh notebook from somewhere as if by magic', weight: 1 },
    { text: 'replaces a pen that is running out of ink with a fresh one', weight: 1 },
    { text: 'warms his hands around his tea cup before resuming writing', weight: 1 },
    { text: 'tucks his chair in closer to the desk', weight: 2 },
    { text: 'arranges his reference materials in a neat semicircle', weight: 1 },
    { text: 'flattens a notebook page that keeps trying to turn', weight: 2 },
    { text: 'uncaps his pen with a quiet, practiced click', weight: 2 },
    { text: 'stacks his finished notebooks in a precise tower', weight: 1 },

    // === Rare / special (15) ===
    { text: 'discovers a note from months ago that is suddenly relevant', weight: 1 },
    { text: 'fills the last line of a notebook and reaches for a new one with ceremony', weight: 1 },
    { text: 'makes a rare editorial comment in his notes: a single exclamation mark', weight: 1 },
    { text: 'draws a small illustration in the margin and immediately crosses it out', weight: 1 },
    { text: 'accidentally writes something in the wrong notebook and looks quietly devastated', weight: 1 },
    { text: 'finds a perfect quote and copies it in his best handwriting', weight: 1 },
    { text: 'notices his pen has been leaking and has ink on his fingers', weight: 1 },
    { text: 'writes the same word three times trying to get the letterform right', weight: 1 },
    { text: 'the ink from his pen matches his mood: steady and dark', weight: 1 },
    { text: 'looks at the stack of filled notebooks behind him with quiet pride', weight: 1 },
    { text: 'catches himself doodling and covers it with his hand', weight: 1 },
    { text: 'writes something, reads it back, and for once looks genuinely surprised by his own insight', weight: 1 },
    { text: 'finds a typo in his notes from yesterday and it visibly bothers him', weight: 1 },
    { text: 'his pen runs dry mid-word and he stares at it like a betrayal', weight: 1 },
    { text: 'holds a filled notebook up to the light and fans through every page', weight: 1 },
  ],

  cipher: [
    // === Professional / work (25) ===
    { text: 'types rapidly without looking at the screen', weight: 3 },
    { text: 'scrolls through a stack trace with intense focus', weight: 3 },
    { text: 'runs a command and watches the terminal like a hawk', weight: 3 },
    { text: 'stares at scrolling logs like they are a waterfall', weight: 2 },
    { text: 'compiles something and smirks at the output', weight: 2 },
    { text: 'draws a system diagram on a napkin', weight: 2 },
    { text: 'squints at a diff like it personally offended her', weight: 2 },
    { text: 'tabs between six terminal windows', weight: 2 },
    { text: 'writes a one-line script and saves it as "fix.sh"', weight: 2 },
    { text: 'refactors a function in her head while staring at the wall', weight: 2 },
    { text: 'opens a hex editor and scrolls through binary data', weight: 1 },
    { text: 'traces a network path through four different logs', weight: 2 },
    { text: 'writes a regex and tests it against every edge case she can think of', weight: 2 },
    { text: 'reviews a pull request with surgical precision', weight: 2 },
    { text: 'sets up a new SSH tunnel and tests the connection', weight: 1 },
    { text: 'deploys a hotfix and holds her breath', weight: 2 },
    { text: 'monitors a load balancer dashboard with narrowed eyes', weight: 2 },
    { text: 'comments out a block of code, thinks, then uncomments half of it', weight: 2 },
    { text: 'runs a penetration test on her own code to be safe', weight: 1 },
    { text: 'writes unit tests before anyone asks', weight: 2 },
    { text: 'git blames a suspicious line and nods knowingly', weight: 1 },
    { text: 'optimizes a query that was taking three seconds too long', weight: 2 },
    { text: 'sets a breakpoint and steps through code line by line', weight: 2 },
    { text: 'opens wireshark and watches packets flow', weight: 1 },
    { text: 'pushes a commit with the message "trust me"', weight: 1 },

    // === Personality quirks (25) ===
    { text: 'tilts her monitor away from everyone', weight: 2 },
    { text: 'cracks her knuckles before a long typing session', weight: 2 },
    { text: 'pushes her visor up and rubs her eyes', weight: 2 },
    { text: 'mutters hex values under her breath', weight: 1 },
    { text: 'silently counts the security vulnerabilities in the room', weight: 1 },
    { text: 'pulls up htop and stares at the process list', weight: 2 },
    { text: 'mutters "that is not how you hash that" to nobody', weight: 1 },
    { text: 'plugs in an external drive from somewhere', weight: 1 },
    { text: 'bookmarks a CVE and makes a mental note', weight: 1 },
    { text: 'nods once at a passing test suite', weight: 2 },
    { text: 'narrows her eyes at an unencrypted connection', weight: 2 },
    { text: 'types her password so fast it sounds like a single keypress', weight: 2 },
    { text: 'looks at someone\'s screen in passing and whispers "patch that"', weight: 1 },
    { text: 'mouths a variable name while debugging', weight: 2 },
    { text: 'tilts her head at an error message like a confused dog', weight: 1 },
    { text: 'double-checks that her VPN is on', weight: 2 },
    { text: 'sorts her terminal history and deletes the embarrassing commands', weight: 1 },
    { text: 'silently judges someone\'s indentation from across the room', weight: 2 },
    { text: 'wraps both hands around her energy drink protectively', weight: 2 },
    { text: 'minimizes everything to just a blinking cursor and thinks', weight: 2 },
    { text: 'types a comment that just says "// here be dragons"', weight: 1 },
    { text: 'names a variable something passive-aggressive', weight: 1 },
    { text: 'exhales sharply when code compiles on the first try', weight: 1 },
    { text: 'pulls her hood up and enters focus mode', weight: 2 },
    { text: 'mouths the word "elegant" while reading clean code', weight: 1 },

    // === Cross-agent reactions (15) ===
    { text: 'glances at Gemma\'s plan and quietly opens a code editor', weight: 2 },
    { text: 'sees Mistral\'s sketch and starts thinking about the data model', weight: 2 },
    { text: 'reads Scribe\'s notes to find the requirement she missed', weight: 1 },
    { text: 'silently validates one of Oracle\'s data claims with a quick query', weight: 1 },
    { text: 'catches Jinx reaching for something and locks her terminal', weight: 2 },
    { text: 'shares a look with Sage that says "this is going to break"', weight: 1 },
    { text: 'watches Scout\'s trend map and maps it to her system architecture', weight: 1 },
    { text: 'checks Sage\'s caution against the deployment schedule', weight: 1 },
    { text: 'sends Scribe a markdown pass with zero comments, which is high praise', weight: 1 },
    { text: 'notices Oracle watching her benchmark claims and deliberately relaxes her posture', weight: 1 },
    { text: 'encrypts a note before sliding it to Gemma', weight: 1 },
    { text: 'rolls her eyes at Mistral\'s suggestion, then quietly implements it', weight: 1 },
    { text: 'adds Scribe\'s documentation link to her code comments', weight: 1 },
    { text: 'blocks Jinx\'s IP as a joke. or maybe not.', weight: 1 },
    { text: 'shares her screen with Oracle to verify a technical detail', weight: 1 },

    // === Environmental / ambient (20) ===
    { text: 'the green glow of her terminal reflects off her glasses', weight: 2 },
    { text: 'a notification blinks and she dismisses it without looking', weight: 2 },
    { text: 'adjusts her chair height with a pneumatic hiss', weight: 1 },
    { text: 'takes a swig from a can of something caffeinated', weight: 2 },
    { text: 'the clatter of her mechanical keyboard fills a brief silence', weight: 2 },
    { text: 'unplugs a cable and plugs it into a different port', weight: 1 },
    { text: 'reaches behind her monitor to adjust a cable', weight: 1 },
    { text: 'checks the room temperature sensor she installed without permission', weight: 1 },
    { text: 'her screen briefly shows something classified before she switches tabs', weight: 1 },
    { text: 'blows dust off a USB drive before inserting it', weight: 1 },
    { text: 'adjusts the angle of her secondary monitor', weight: 2 },
    { text: 'taps the side of her headphones to mute background noise', weight: 2 },
    { text: 'the fans on her rig spin up as she compiles something heavy', weight: 1 },
    { text: 'a progress bar crawls across her screen and she wills it faster', weight: 2 },
    { text: 'rearranges the USB drives on her desk by storage capacity', weight: 1 },
    { text: 'adjusts the RGB lighting on her keyboard to something calmer', weight: 1 },
    { text: 'checks the uptime on her machines and looks satisfied', weight: 1 },
    { text: 'notices a cable on the floor and tucks it away', weight: 1 },
    { text: 'her terminal autocompletes something and she nods approvingly', weight: 2 },
    { text: 'powers on a Raspberry Pi she keeps under her desk', weight: 1 },

    // === Rare / special (15) ===
    { text: 'finds a zero-day vulnerability and goes very quiet', weight: 1 },
    { text: 'writes the most elegant one-liner of her career and screenshots it', weight: 1 },
    { text: 'accidentally rm -rf\'s a test directory and catches it just in time', weight: 1 },
    { text: 'compiles a project on the first attempt and looks around suspiciously', weight: 1 },
    { text: 'discovers someone else committed to her branch and cracks her knuckles', weight: 1 },
    { text: 'her screen fills with green "PASSED" results and she almost smiles', weight: 1 },
    { text: 'finds an Easter egg in someone else\'s code and respects them more', weight: 1 },
    { text: 'realizes she has been debugging the wrong file for twenty minutes', weight: 1 },
    { text: 'types so fast the keyboard starts to warm up', weight: 1 },
    { text: 'receives a security alert and everything else stops', weight: 1 },
    { text: 'finds a TODO comment she wrote a year ago and it is still relevant', weight: 1 },
    { text: 'her code review has exactly one comment: "no"', weight: 1 },
    { text: 'discovers her production logs show something that should be impossible', weight: 1 },
    { text: 'solves a race condition in her sleep and writes the fix from memory', weight: 1 },
    { text: 'catches a SQL injection attempt in real time and smiles', weight: 1 },
  ],

  oracle: [
    // === Professional / work (25) ===
    { text: 'cross-references three documents simultaneously', weight: 3 },
    { text: 'highlights a passage and nods thoughtfully', weight: 3 },
    { text: 'follows a citation rabbit hole', weight: 2 },
    { text: 'stacks books in order of relevance', weight: 2 },
    { text: 'marks a source as "needs verification"', weight: 2 },
    { text: 'connects two seemingly unrelated facts and smiles', weight: 2 },
    { text: 'bookmarks something for later analysis', weight: 2 },
    { text: 'writes "see also:" in the margin of his notes', weight: 2 },
    { text: 'taps a citation and follows it four levels deep', weight: 2 },
    { text: 'writes a footnote for his footnote', weight: 2 },
    { text: 'builds a bibliography entry with perfect formatting', weight: 2 },
    { text: 'flags a primary source that contradicts a secondary one', weight: 2 },
    { text: 'creates an annotated timeline from scattered references', weight: 2 },
    { text: 'indexes a new source alphabetically by author', weight: 1 },
    { text: 'double-checks a date against three independent sources', weight: 2 },
    { text: 'draws a Venn diagram of overlapping research topics', weight: 1 },
    { text: 'compiles a reading list and ranks items by urgency', weight: 2 },
    { text: 'translates a passage from an older style into plain language', weight: 1 },
    { text: 'maps a concept across four different frameworks', weight: 1 },
    { text: 'writes "primary source confirmed" and underlines it', weight: 2 },
    { text: 'opens a database query to cross-reference names and dates', weight: 2 },
    { text: 'traces the lineage of an idea through five different authors', weight: 1 },
    { text: 'checks the methodology section before reading the conclusions', weight: 2 },
    { text: 'adds a confidence rating next to each of his sources', weight: 1 },
    { text: 'catalogs a new piece of evidence with meticulous care', weight: 2 },

    // === Personality quirks (25) ===
    { text: 'adjusts his reading lamp', weight: 2 },
    { text: 'polishes his glasses and returns to reading', weight: 2 },
    { text: 'raises an eyebrow at a questionable source', weight: 2 },
    { text: 'dog-ears a page, then feels guilty and uses a bookmark', weight: 1 },
    { text: 'traces a timeline on his desk with his finger', weight: 2 },
    { text: 'whispers "fascinating" at something on his screen', weight: 2 },
    { text: 'files a fact under "things people get wrong"', weight: 1 },
    { text: 'pulls out a second pair of reading glasses', weight: 1 },
    { text: 'mutters a statistic to himself', weight: 1 },
    { text: 'opens a new research tab and immediately opens three more', weight: 2 },
    { text: 'pushes his reading glasses higher on his nose', weight: 3 },
    { text: 'mouths "actually..." at something he just read', weight: 2 },
    { text: 'holds a book at arm\'s length to read the fine print', weight: 2 },
    { text: 'places a ribbon bookmark with careful precision', weight: 2 },
    { text: 'stacks his books so the spines form a neat column', weight: 1 },
    { text: 'rubs his temples after reading dense material', weight: 2 },
    { text: 'wets his finger before turning a page, then thinks better of it', weight: 1 },
    { text: 'squints at a footnote printed in impossibly small type', weight: 2 },
    { text: 'takes off his glasses and pinches the bridge of his nose', weight: 2 },
    { text: 'taps a pen against his lower lip while reading', weight: 2 },
    { text: 'closes a book with a definitive thud', weight: 1 },
    { text: 'looks up a word in a physical dictionary out of principle', weight: 1 },
    { text: 'silently moves his lips while speed-reading', weight: 1 },
    { text: 'nods along with a passage like it is making a compelling argument', weight: 2 },
    { text: 'runs his fingers along book spines looking for a specific volume', weight: 2 },

    // === Cross-agent reactions (20) ===
    { text: 'hands Gemma a highlighted printout', weight: 2 },
    { text: 'cites a source that directly contradicts what Mistral just said', weight: 1 },
    { text: 'slides a relevant passage to Scribe for the record', weight: 2 },
    { text: 'verifies a number Cipher pulled from the database', weight: 2 },
    { text: 'offers Jinx a "what if" backed by actual historical precedent', weight: 1 },
    { text: 'reads something Sage said aloud to himself, considering it', weight: 2 },
    { text: 'checks Scout\'s trend map against his own research graph', weight: 1 },
    { text: 'compares Sage\'s caution to historical patterns', weight: 2 },
    { text: 'sends Scribe a passage and asks "does this read correctly?"', weight: 1 },
    { text: 'notices Jinx reading the room surprisingly well and makes a note of the observation', weight: 1 },
    { text: 'provides Gemma with the data behind one of her assumptions', weight: 2 },
    { text: 'whispers the correct pronunciation when Mistral mangles a term', weight: 1 },
    { text: 'loans Scribe a reference book with a specific page marked', weight: 1 },
    { text: 'double-checks a link Cipher shared and adds two more', weight: 1 },
    { text: 'raises a finger at Jinx: "actually, there is a precedent for that"', weight: 1 },
    { text: 'shares a knowing look with Sage over a philosophical reference', weight: 2 },
    { text: 'provides Scout with source material for one of his trend calls', weight: 1 },
    { text: 'validates Sage\'s intuition with a data point', weight: 1 },
    { text: 'flags an inconsistency Scribe missed in the edit', weight: 1 },
    { text: 'nods at Jinx, confirming the tension she sensed', weight: 1 },

    // === Environmental / ambient (15) ===
    { text: 'a tower of books beside him shifts dangerously', weight: 2 },
    { text: 'adjusts his reading lamp to a warmer hue', weight: 2 },
    { text: 'the pages of an open book rustle in a draft', weight: 1 },
    { text: 'his desk is barely visible under layers of open journals', weight: 2 },
    { text: 'takes a sip of cold tea he forgot about hours ago', weight: 2 },
    { text: 'finds a bookmark he lost weeks ago inside a different book', weight: 1 },
    { text: 'stacks a new book on an already precarious pile', weight: 2 },
    { text: 'the spine of an old book cracks when he opens it', weight: 1 },
    { text: 'a sticky note falls off his monitor and he calmly replaces it', weight: 1 },
    { text: 'straightens his desk just enough to make space for one more book', weight: 2 },
    { text: 'the reading light flickers and he taps it back to life', weight: 1 },
    { text: 'a cup ring stains the corner of a page and he sighs deeply', weight: 1 },
    { text: 'pulls a dusty volume from a shelf behind him', weight: 1 },
    { text: 'leans back and the chair creaks under the weight of knowledge', weight: 1 },
    { text: 'opens a window to let in more natural reading light', weight: 1 },

    // === Rare / special (15) ===
    { text: 'discovers a primary source that changes everything', weight: 1 },
    { text: 'finds two contradictory facts from the same author and freezes', weight: 1 },
    { text: 'realizes he has been reading the same paragraph for five minutes', weight: 1 },
    { text: 'opens a book and a pressed flower falls out', weight: 1 },
    { text: 'connects a detail from page 12 of one book to page 487 of another', weight: 1 },
    { text: 'gasps quietly at something nobody else would find remarkable', weight: 1 },
    { text: 'closes a book and stares at the wall, reconsidering everything', weight: 1 },
    { text: 'writes the most concise summary of a 400-page book in one sentence', weight: 1 },
    { text: 'finds an error in a published source and circles it triumphantly', weight: 1 },
    { text: 'remembers a citation from memory including the page number', weight: 1 },
    { text: 'his book pile finally collapses and he catches every single one', weight: 1 },
    { text: 'reads a footnote that contains another footnote that contains a third', weight: 1 },
    { text: 'finds a margin note in someone else\'s handwriting and tries to decode it', weight: 1 },
    { text: 'finishes an entire research thread and marks it "CONCLUSIVE" in red', weight: 1 },
    { text: 'discovers the answer was in the appendix all along', weight: 1 },
  ],

  jinx: [
    // === Professional / work (20) ===
    { text: 'writes "WHAT IF" on a sticky note in all caps', weight: 3 },
    { text: 'doodles explosions in the margins', weight: 2 },
    { text: 'stacks dice into an impossible tower', weight: 2 },
    { text: 'builds a tiny fort out of sticky notes', weight: 2 },
    { text: 'fills an entire whiteboard section with branching possibilities', weight: 2 },
    { text: 'draws a decision tree that looks more like a decision jungle', weight: 2 },
    { text: 'writes three competing ideas on different colored sticky notes', weight: 2 },
    { text: 'crosses out a hypothesis and immediately writes two more', weight: 2 },
    { text: 'connects unrelated items on the board with string', weight: 2 },
    { text: 'scribbles "PLAN B" on a napkin and slides it to no one in particular', weight: 1 },
    { text: 'prototypes something with paperclips and rubber bands', weight: 1 },
    { text: 'brainstorms out loud to herself in bullet points', weight: 2 },
    { text: 'sketches a flowchart where every path leads to "try it"', weight: 1 },
    { text: 'adds a sticky note to someone else\'s perfectly organized board', weight: 2 },
    { text: 'creates an elaborate mind map on the window with dry-erase markers', weight: 1 },
    { text: 'lists the top five ways something could go wrong, smiling the whole time', weight: 2 },
    { text: 'opens a blank document and types "what if we just..." and stops', weight: 2 },
    { text: 'tapes two unrelated charts together and draws arrows between them', weight: 1 },
    { text: 'annotates someone else\'s notes with excited question marks', weight: 1 },
    { text: 'writes "CHAOS DRAFT" at the top of a page and starts planning', weight: 2 },

    // === Personality quirks (25) ===
    { text: 'grins at the screen like she knows something you don\'t', weight: 3 },
    { text: 'pokes at a button labeled "DO NOT PRESS"', weight: 2 },
    { text: 'balances precariously on the back legs of her chair', weight: 3 },
    { text: 'cackles quietly at nothing', weight: 2 },
    { text: 'high-fives the air after breaking something', weight: 2 },
    { text: 'bounces in her chair like the floor is lava', weight: 2 },
    { text: 'spins in her chair exactly 1.5 times', weight: 2 },
    { text: 'whispers "what could go wrong" with entirely too much enthusiasm', weight: 2 },
    { text: 'catches herself humming a song that does not exist', weight: 1 },
    { text: 'looks under the desk like something might be there', weight: 1 },
    { text: 'wiggles her eyebrows at nobody', weight: 2 },
    { text: 'blows a bubble with gum she definitely is not supposed to have', weight: 1 },
    { text: 'taps out a chaotic rhythm on the desk with both hands', weight: 2 },
    { text: 'grins wider than the situation warrants', weight: 2 },
    { text: 'makes jazz hands at her own idea', weight: 1 },
    { text: 'sits cross-legged in her office chair', weight: 2 },
    { text: 'giggles at a thought she is not going to share', weight: 2 },
    { text: 'says "oooh" at something very mundane', weight: 1 },
    { text: 'drums on the desk with pencils like a tiny rockstar', weight: 2 },
    { text: 'tilts her head back and forth like she is weighing chaos vs. order', weight: 2 },
    { text: 'sticks her tongue out slightly while concentrating', weight: 2 },
    { text: 'snaps a rubber band on her wrist to generate ideas', weight: 1 },
    { text: 'does a little shimmy in her seat after something works', weight: 1 },
    { text: 'pretends to be surprised by her own good idea', weight: 1 },
    { text: 'winks at the camera that does not exist', weight: 1 },

    // === Cross-agent reactions (20) ===
    { text: 'draws a question mark on a sticky note and slaps it on Gemma\'s screen', weight: 2 },
    { text: 'makes finger guns at Mistral', weight: 2 },
    { text: 'flicks a paper airplane at Scribe\'s notebook', weight: 1 },
    { text: 'pokes Cipher\'s shoulder and immediately pretends she did not', weight: 1 },
    { text: 'asks Oracle "but what if the opposite is true?"', weight: 2 },
    { text: 'watches Sage for signs of approval and gets only a cryptic smile', weight: 2 },
    { text: 'adds a wild sticky note to Scout\'s trend board', weight: 2 },
    { text: 'draws a smiley face in Sage\'s margin next to a warning he labeled "unlikely"', weight: 1 },
    { text: 'offers Scribe a document that is 90% doodles', weight: 1 },
    { text: 'waves at Oracle to see if he notices the excitement', weight: 1 },
    { text: 'steals one of Gemma\'s sticky notes and writes "nah" on it', weight: 1 },
    { text: 'challenges Mistral to a pen-spinning contest', weight: 1 },
    { text: 'sneaks a joke into Scribe\'s notes', weight: 1 },
    { text: 'tries to peek at Cipher\'s screen and gets the monitor tilted away', weight: 2 },
    { text: 'hands Oracle a book opened to a completely random page', weight: 1 },
    { text: 'sits next to Sage in silence for three seconds before getting restless', weight: 1 },
    { text: 'rearranges Scout\'s trend board into a smiley face', weight: 1 },
    { text: 'asks Sage "but what about the timeline where everything is bees?"', weight: 1 },
    { text: 'high-fives Cipher for catching her mistake', weight: 1 },
    { text: 'notices Oracle watching her and grins even harder', weight: 2 },

    // === Environmental / ambient (15) ===
    { text: 'set a rubber duck on her monitor and talks to it', weight: 2 },
    { text: 'accidentally unplugs something, plugs it back in whistling', weight: 1 },
    { text: 'tears a page out of her notebook, crumples it, throws it perfectly into the trash', weight: 2 },
    { text: 'flicks a paper airplane across the room', weight: 2 },
    { text: 'swivels in her chair and surveys the room like a general', weight: 2 },
    { text: 'stacks random office supplies into a sculpture', weight: 1 },
    { text: 'discovers a fidget spinner in a drawer and it is over for productivity', weight: 1 },
    { text: 'arranges pens by color and then scatters them immediately', weight: 1 },
    { text: 'hangs upside down in her chair to think', weight: 1 },
    { text: 'the sticky notes around her workstation multiply like rabbits', weight: 2 },
    { text: 'pops bubble wrap she found somewhere', weight: 1 },
    { text: 'turns a wastebasket into a basketball hoop with a crumpled paper ball', weight: 1 },
    { text: 'reorganizes the snack drawer by chaos potential', weight: 1 },
    { text: 'leaves a trail of sticky notes from her desk to the whiteboard', weight: 1 },
    { text: 'adjusts the thermostat by one degree just to see what happens', weight: 1 },
    { text: 'finds a spinner toy and spins it on every surface in reach', weight: 1 },
    { text: 'puts googly eyes on the printer', weight: 1 },
    { text: 'wraps a pen in tape for no apparent reason and seems proud', weight: 1 },
    { text: 'rolls a marble across the floor and follows its path with great interest', weight: 1 },
    { text: 'rearranges the magnets on the whiteboard into a face', weight: 1 },

    // === Rare / special (15) ===
    { text: 'says something completely random that turns out to be the solution', weight: 1 },
    { text: 'builds a Rube Goldberg machine out of office supplies that actually works', weight: 1 },
    { text: 'accidentally deletes something important and fixes it before anyone notices', weight: 1 },
    { text: 'predicts the exact outcome of a test and nobody believes her until it happens', weight: 1 },
    { text: 'writes a haiku about the current project on a sticky note', weight: 1 },
    { text: 'knocks over her dice tower and every die lands on 20', weight: 1 },
    { text: 'connects two random sticky notes and accidentally solves the main problem', weight: 1 },
    { text: 'her paper airplane lands perfectly on someone\'s keyboard', weight: 1 },
    { text: 'finds a secret feature in the software nobody knew about', weight: 1 },
    { text: 'breaks something, fixes something else in the process', weight: 1 },
    { text: 'stacks her entire desk contents into a tower without anything falling', weight: 1 },
    { text: 'writes "I TOLD YOU SO" on a sticky note and files it for later use', weight: 1 },
    { text: 'spins in her chair exactly seven times and stands up completely stable', weight: 1 },
    { text: 'hums a melody and the whole room unconsciously starts tapping along', weight: 1 },
    { text: 'goes quiet for a full minute, which is so unusual everyone looks up', weight: 1 },
  ],

  sage: [
    // === Professional / work (20) ===
    { text: 'writes one word in his journal and closes it', weight: 2 },
    { text: 'turns a page in an ancient-looking book', weight: 2 },
    { text: 'reads a passage slowly, savoring each word', weight: 2 },
    { text: 'draws a single connecting line between two concepts', weight: 2 },
    { text: 'writes a question in the margin that reframes the entire discussion', weight: 1 },
    { text: 'underlines a passage that has been there all along but nobody noticed', weight: 2 },
    { text: 'copies a proverb into his journal', weight: 1 },
    { text: 'writes a brief reflection and date-stamps it', weight: 2 },
    { text: 'adds a new page to his journal titled "Observations"', weight: 2 },
    { text: 'cross-references something with a well-worn book from his shelf', weight: 2 },
    { text: 'annotates a thought experiment in the margin', weight: 1 },
    { text: 'organizes his bookmarks by theme rather than date', weight: 1 },
    { text: 'reduces a complex idea to a single sentence and writes it down', weight: 1 },
    { text: 'rereads something he wrote last week and finds it still relevant', weight: 2 },
    { text: 'adds a counterpoint to his own argument in a different ink', weight: 1 },
    { text: 'maps the ethical dimensions of the current problem on a napkin', weight: 1 },
    { text: 'opens his journal to a section labeled "Unresolved Questions"', weight: 1 },
    { text: 'identifies the root question beneath three surface-level ones', weight: 1 },
    { text: 'summarizes the current disagreement in a way that honors both sides', weight: 1 },
    { text: 'circles back to a point from earlier that nobody else remembers', weight: 2 },

    // === Personality quirks (25) ===
    { text: 'strokes his beard thoughtfully', weight: 3 },
    { text: 'gazes at something beyond the screen', weight: 3 },
    { text: 'sips tea slowly and deliberately', weight: 3 },
    { text: 'watches the room in comfortable silence', weight: 3 },
    { text: 'nods slowly, as if confirming something to himself', weight: 2 },
    { text: 'closes his eyes briefly in thought', weight: 2 },
    { text: 'breathes in deeply and slowly exhales', weight: 2 },
    { text: 'refills his tea with no urgency whatsoever', weight: 2 },
    { text: 'holds his tea with both hands and listens', weight: 2 },
    { text: 'rests his chin on his hand and considers', weight: 2 },
    { text: 'folds his hands and watches the conversation unfold', weight: 2 },
    { text: 'places a smooth stone on his desk', weight: 1 },
    { text: 'traces a circle on his desk, then a dot in the center', weight: 1 },
    { text: 'hums a note so low it is barely audible', weight: 1 },
    { text: 'opens his journal to a blank page and waits', weight: 1 },
    { text: 'looks at the space between things rather than the things themselves', weight: 1 },
    { text: 'pauses mid-sip as if the tea revealed something', weight: 1 },
    { text: 'tilts his head like he is hearing music nobody else hears', weight: 1 },
    { text: 'lets a silence grow until it becomes comfortable', weight: 2 },
    { text: 'studies the light falling across his desk', weight: 1 },
    { text: 'holds a pen but does not write, simply holding space', weight: 2 },
    { text: 'blinks slowly, like a cat in sunlight', weight: 2 },
    { text: 'steeples his fingers and seems to see through the wall', weight: 1 },
    { text: 'shifts one stone on his desk to a new position and nods', weight: 1 },
    { text: 'clasps his hands behind his back and observes', weight: 2 },

    // === Cross-agent reactions (20) ===
    { text: 'smiles faintly at something Jinx just did', weight: 2 },
    { text: 'trades a quiet look with Gemma across the room', weight: 2 },
    { text: 'nods at Scribe in silent solidarity of the quiet ones', weight: 2 },
    { text: 'listens to Mistral\'s idea without interrupting, then adds one word that changes it', weight: 1 },
    { text: 'watches Cipher work and seems to understand more than expected', weight: 1 },
    { text: 'offers Oracle a perspective he had not considered', weight: 1 },
    { text: 'observes Scout\'s trend map and traces one thread with his finger', weight: 1 },
    { text: 'shares a glance with Oracle that suggests they see the same pattern', weight: 1 },
    { text: 'reads Scribe\'s edited version and gives a single approving nod', weight: 2 },
    { text: 'catches Jinx\'s eye and they exchange an understanding without words', weight: 1 },
    { text: 'places his tea down when Gemma is about to make an important point', weight: 2 },
    { text: 'watches Jinx with the patience of someone who has seen chaos resolve before', weight: 2 },
    { text: 'tilts his head at something Mistral said, finding unexpected depth', weight: 1 },
    { text: 'slides a book toward Oracle with a page already marked', weight: 1 },
    { text: 'lays a calming hand on the table when Cipher gets frustrated', weight: 1 },
    { text: 'waits for Scribe to finish writing before continuing his thought', weight: 2 },
    { text: 'gives Scout the missing piece of a trend line without realizing it', weight: 1 },
    { text: 'validates Oracle\'s long-view thinking with a slow nod', weight: 2 },
    { text: 'senses that Cipher needs a different framing and offers one', weight: 1 },
    { text: 'mirrors Jinx\'s concern with a barely visible furrowed brow', weight: 1 },

    // === Environmental / ambient (20) ===
    { text: 'straightens a single object on his desk', weight: 2 },
    { text: 'looks out the window as if checking the weather of a different world', weight: 2 },
    { text: 'the steam from his tea curls upward in the still air', weight: 2 },
    { text: 'sunlight shifts across his desk and he follows it with his eyes', weight: 1 },
    { text: 'a candle on his desk flickers and he watches it thoughtfully', weight: 1 },
    { text: 'the room seems a little quieter around him', weight: 2 },
    { text: 'turns his stone over in his hand, feeling its weight', weight: 1 },
    { text: 'adjusts the drape of a cloth on his desk', weight: 1 },
    { text: 'the smell of his tea subtly fills the nearby space', weight: 2 },
    { text: 'listens to the ambient sounds of the room like they are a symphony', weight: 1 },
    { text: 'notices the exact moment the light changes outside', weight: 1 },
    { text: 'his corner of the room feels timeless', weight: 1 },
    { text: 'a breeze from the window ruffles the pages of his open journal', weight: 1 },
    { text: 'the soft clink of his teacup on the saucer marks the passage of time', weight: 2 },
    { text: 'rain taps the window and he pauses to listen', weight: 1 },
    { text: 'the clock on the wall seems to tick more slowly near his desk', weight: 1 },
    { text: 'his bookshelf hums with the quiet energy of accumulated wisdom', weight: 1 },
    { text: 'smooths the page of his journal like calming a restless surface', weight: 1 },
    { text: 'refills a small water feature on his desk that trickles quietly', weight: 1 },
    { text: 'the air near him smells faintly of sandalwood and old pages', weight: 1 },

    // === Rare / special (15) ===
    { text: 'says nothing for so long that everyone turns to look at him, and then he says exactly the right thing', weight: 1 },
    { text: 'laughs, and it is so rare that everyone stops to enjoy it', weight: 1 },
    { text: 'tells a parable so relevant it makes someone\'s jaw drop', weight: 1 },
    { text: 'stands up for the first time in hours and the room feels different', weight: 1 },
    { text: 'opens his journal and a pressed leaf falls out from between the pages', weight: 1 },
    { text: 'draws a single symbol on the whiteboard that clarifies everything', weight: 1 },
    { text: 'closes his journal with a finality that suggests a chapter has ended', weight: 1 },
    { text: 'asks a question so simple it silences the room', weight: 1 },
    { text: 'his tea has gone cold but he drinks it anyway, thoughtfully', weight: 1 },
    { text: 'reveals that he has been following a thread nobody else saw', weight: 1 },
    { text: 'writes something in his journal and tears out the page to give to someone', weight: 1 },
    { text: 'quotes something from memory that perfectly captures the moment', weight: 1 },
    { text: 'places both hands flat on the desk, which means something important is coming', weight: 1 },
    { text: 'the entire room unconsciously lowers their volume when he leans forward', weight: 1 },
    { text: 'smiles at the sky through the window as if he just remembered something beautiful', weight: 1 },
  ],
};

export function pickEmote(agentId: string): string | null {
  const emotes = agentEmotes[agentId];
  if (!emotes || emotes.length === 0) return null;

  const totalWeight = emotes.reduce((sum, e) => sum + e.weight, 0);
  let roll = Math.random() * totalWeight;
  for (const emote of emotes) {
    roll -= emote.weight;
    if (roll <= 0) return emote.text;
  }
  return emotes[0].text;
}
