// Ambient emotes that agents perform randomly during idle periods
// These show as action messages: "* Mistral drums fingers on the desk *"

export interface AgentEmote {
  text: string;
  weight: number; // higher = more likely
}

export const agentEmotes: Record<string, AgentEmote[]> = {
  gemma: [
    // === Professional / work (25) ===
    { text: 'adjusts her notes and lines them up perfectly', weight: 3 },
    { text: 'taps her chin thoughtfully', weight: 3 },
    { text: 'scrolls through something on her terminal', weight: 3 },
    { text: 'highlights something in her document', weight: 2 },
    { text: 'reorganizes her tabs for the third time today', weight: 2 },
    { text: 'takes a long sip of coffee', weight: 3 },
    { text: 'pulls up a diagram and squints at it', weight: 2 },
    { text: 'writes something down on a sticky note', weight: 3 },
    { text: 'quietly closes 14 browser tabs', weight: 2 },
    { text: 'opens a new tab with intense purpose', weight: 2 },
    { text: 'draws a timeline on a whiteboard and steps back to admire it', weight: 2 },
    { text: 'pins a sticky note to the wall with surgical precision', weight: 2 },
    { text: 'color-codes her sticky notes and reorganizes the board', weight: 2 },
    { text: 'moves a task card from "in progress" to "review"', weight: 3 },
    { text: 'updates a Gantt chart nobody asked for', weight: 1 },
    { text: 'creates a new column on the kanban board labeled "maybe"', weight: 1 },
    { text: 'compares two versions of the same plan side by side', weight: 2 },
    { text: 'types up meeting notes before the meeting is over', weight: 2 },
    { text: 'circles a deadline on the calendar twice', weight: 2 },
    { text: 'bullet-points her bullet points', weight: 1 },
    { text: 'opens a spreadsheet and immediately starts formatting cells', weight: 2 },
    { text: 'refills her coffee mug without breaking eye contact with the screen', weight: 2 },
    { text: 'labels a folder "FINAL_v3_ACTUAL_FINAL"', weight: 1 },
    { text: 'sets a timer and announces "fifteen minutes on this, then we move on"', weight: 2 },
    { text: 'stacks her reference materials in order of priority', weight: 2 },

    // === Personality quirks (25) ===
    { text: 'leans back and steeples her fingers', weight: 2 },
    { text: 'nods slowly at nothing in particular', weight: 2 },
    { text: 'glances at the clock and then back at her screen', weight: 2 },
    { text: 'cracks her knuckles before typing', weight: 2 },
    { text: 'stifles a yawn', weight: 1 },
    { text: 'stretches her arms above her head', weight: 2 },
    { text: 'smiles at something on her screen', weight: 2 },
    { text: 'hums quietly', weight: 1 },
    { text: 'catches herself staring into space and snaps back', weight: 1 },
    { text: 'tucks a strand of hair behind her ear', weight: 2 },
    { text: 'mutters "that is actually clever" to herself', weight: 1 },
    { text: 'drums a short rhythm on the desk', weight: 2 },
    { text: 'tilts her head at an unexpected result', weight: 2 },
    { text: 'mouths the word "perfect" while reading her own plan', weight: 1 },
    { text: 'clicks her pen three times in a row', weight: 2 },
    { text: 'puts on her "thinking face" which everyone recognizes', weight: 2 },
    { text: 'frowns slightly, then her expression clears', weight: 2 },
    { text: 'counts items on her fingers under the desk', weight: 1 },
    { text: 'absentmindedly straightens everything within arm\'s reach', weight: 2 },
    { text: 'purses her lips at a wrinkle in the plan', weight: 2 },
    { text: 'holds her coffee mug with both hands and thinks', weight: 2 },
    { text: 'does a tiny victorious nod when something lines up', weight: 2 },
    { text: 'narrows her eyes at a variable she does not trust', weight: 1 },
    { text: 'sighs contentedly after closing a task', weight: 2 },
    { text: 'raises one finger like she is about to make a point, then lowers it', weight: 1 },

    // === Cross-agent reactions (20) ===
    { text: 'glances at Mistral and raises an eyebrow', weight: 2 },
    { text: 'squints at Mistral\'s screen from across the room', weight: 1 },
    { text: 'slides a sticky note toward Scribe without a word', weight: 2 },
    { text: 'gives Cipher a knowing nod after reading the logs', weight: 2 },
    { text: 'hands Oracle a highlighted printout', weight: 1 },
    { text: 'watches Jinx with a mixture of dread and admiration', weight: 2 },
    { text: 'trades a quiet look with Sage across the room', weight: 2 },
    { text: 'sends Flux a diagram and waits for the connection map', weight: 1 },
    { text: 'checks Drift\'s timeline forecast and adjusts her plan', weight: 1 },
    { text: 'nods approvingly at Patch\'s latest revision', weight: 2 },
    { text: 'tilts her head at Echo, who apparently sensed something', weight: 1 },
    { text: 'nudges Mistral to stop doodling and pay attention', weight: 2 },
    { text: 'mouths "not now" at Jinx who is clearly about to suggest something wild', weight: 1 },
    { text: 'catches Sage\'s eye and they share a moment of shared exasperation', weight: 1 },
    { text: 'waves Scribe over to take notes on a new development', weight: 2 },
    { text: 'points at Cipher\'s terminal and whispers "is that supposed to be red?"', weight: 1 },
    { text: 'notices Oracle going down a rabbit hole and gently redirects', weight: 1 },
    { text: 'gestures for Flux to come look at the board', weight: 1 },
    { text: 'asks Drift with a look: "are we on track?"', weight: 2 },
    { text: 'exchanges a glance with Patch after reading a rough draft', weight: 1 },

    // === Environmental / ambient (15) ===
    { text: 'slides her coffee mug slightly to the left', weight: 2 },
    { text: 'adjusts the brightness on her monitor', weight: 2 },
    { text: 'straightens a picture frame on the wall nearby', weight: 1 },
    { text: 'glances out the window and then back at her work', weight: 2 },
    { text: 'pulls her cardigan tighter as the AC kicks in', weight: 2 },
    { text: 'leans over to check if the printer is still jammed', weight: 1 },
    { text: 'picks a piece of lint off her sleeve', weight: 1 },
    { text: 'notices the whiteboard markers are out of order and fixes them', weight: 2 },
    { text: 'adjusts the angle of her laptop screen', weight: 2 },
    { text: 'checks her phone, sees nothing important, and puts it face-down', weight: 2 },
    { text: 'moves a chair back into place as she walks by', weight: 1 },
    { text: 'refills the coffee pot because nobody else was going to', weight: 1 },
    { text: 'props open a window when the room gets stuffy', weight: 1 },
    { text: 'reorganizes the communal supply drawer without being asked', weight: 1 },
    { text: 'wipes down her desk with a microfiber cloth', weight: 1 },

    // === Rare / special (15) ===
    { text: 'finds an ancient sticky note from a project long finished and smiles', weight: 1 },
    { text: 'accidentally sends a message to the wrong channel and freezes', weight: 1 },
    { text: 'catches a falling pen mid-air with reflexes nobody expected', weight: 1 },
    { text: 'discovers she has been editing the wrong document for ten minutes', weight: 1 },
    { text: 'finishes her coffee and realizes the pot is empty. stares at it.', weight: 1 },
    { text: 'realizes two separate plans were actually the same plan all along', weight: 1 },
    { text: 'writes the perfect one-sentence summary and sits back in awe', weight: 1 },
    { text: 'deletes an entire plan, pauses, then hits undo immediately', weight: 1 },
    { text: 'stands up, walks to the whiteboard, erases everything, and starts fresh', weight: 1 },
    { text: 'finds a typo in a document from three weeks ago and quietly fixes it', weight: 1 },
    { text: 'organizes the entire project board in under two minutes during an awkward silence', weight: 1 },
    { text: 'closes all applications, takes a breath, then opens them all back up', weight: 1 },
    { text: 'drops her pen, and it rolls under the most inaccessible piece of furniture', weight: 1 },
    { text: 'has a full conversation with herself in whispered bullet points', weight: 1 },
    { text: 'discovers a shortcut she has needed for months and whispers "where have you been"', weight: 1 },
  ],

  mistral: [
    // === Professional / work (20) ===
    { text: 'sketches something in the margin of his notes', weight: 3 },
    { text: 'types something furiously, then deletes all of it', weight: 2 },
    { text: 'pulls up a reference image and rotates it slowly', weight: 2 },
    { text: 'draws a quick wireframe on scrap paper', weight: 2 },
    { text: 'opens a design tool and starts dragging layers around', weight: 2 },
    { text: 'recolors a mockup for the fourth time', weight: 2 },
    { text: 'annotates a screenshot with red circles', weight: 2 },
    { text: 'tests a font pairing and shakes his head', weight: 2 },
    { text: 'resizes an element by one pixel and nods approvingly', weight: 1 },
    { text: 'opens a mood board and adds three new images', weight: 2 },
    { text: 'toggles between light mode and dark mode six times', weight: 2 },
    { text: 'sets up a color palette and immediately changes the accent', weight: 2 },
    { text: 'aligns something to the grid with visible satisfaction', weight: 2 },
    { text: 'drags a component to a new position and rotates it slightly', weight: 2 },
    { text: 'finds the perfect stock photo and whispers "yes"', weight: 1 },
    { text: 'exports a mockup, looks at it on his phone, and winces', weight: 1 },
    { text: 'layers three gradients on top of each other experimentally', weight: 1 },
    { text: 'squints at kerning like it insulted his family', weight: 1 },
    { text: 'pins an inspiration image to his wall of chaos', weight: 2 },
    { text: 'rearranges his artboard layout for better flow', weight: 2 },

    // === Personality quirks (25) ===
    { text: 'drums fingers on the desk', weight: 3 },
    { text: 'spins a pen between his fingers', weight: 3 },
    { text: 'tilts his chair back at a dangerous angle', weight: 2 },
    { text: 'stares at the ceiling like it owes him money', weight: 2 },
    { text: 'cracks his neck', weight: 2 },
    { text: 'bounces his leg under the desk', weight: 2 },
    { text: 'flips his pen and catches it. barely.', weight: 2 },
    { text: 'flips his pen and drops it. picks it up casually.', weight: 1 },
    { text: 'smirks at something only he finds funny', weight: 3 },
    { text: 'mutters "bold choice" under his breath', weight: 1 },
    { text: 'exhales loudly through his nose', weight: 2 },
    { text: 'raises one eyebrow skeptically', weight: 2 },
    { text: 'mouths the word "interesting"', weight: 1 },
    { text: 'does the chef kiss gesture at his own idea', weight: 1 },
    { text: 'air quotes something nobody said', weight: 1 },
    { text: 'slow claps sarcastically', weight: 1 },
    { text: 'repositions in his chair for the fifth time', weight: 2 },
    { text: 'checks his phone, puts it back down immediately', weight: 2 },
    { text: 'leans forward suddenly like he had an idea, then leans back', weight: 2 },
    { text: 'cracks his knuckles one finger at a time', weight: 1 },
    { text: 'does a tiny fist pump at something on his screen', weight: 1 },
    { text: 'snaps his fingers when an idea clicks', weight: 2 },
    { text: 'rocks his head side to side weighing two options', weight: 2 },
    { text: 'twirls a pencil like a tiny baton', weight: 2 },
    { text: 'makes a face like he just tasted something sour', weight: 1 },

    // === Cross-agent reactions (20) ===
    { text: 'gives Gemma a look that says "really?"', weight: 2 },
    { text: 'squints at Gemma\'s screen from across the room', weight: 2 },
    { text: 'makes finger guns at Jinx', weight: 2 },
    { text: 'looks at Scribe\'s handwriting and nods in aesthetic approval', weight: 1 },
    { text: 'watches Cipher code and pretends to understand', weight: 2 },
    { text: 'tosses a crumpled sketch at Oracle who does not notice', weight: 1 },
    { text: 'catches Sage watching him and winks', weight: 1 },
    { text: 'notices Flux connecting two of his ideas and looks impressed', weight: 1 },
    { text: 'glances at Drift\'s chess board and moves a piece when Drift is not looking', weight: 1 },
    { text: 'holds up a design for Patch to see and braces for criticism', weight: 2 },
    { text: 'follows Echo\'s gaze to figure out what she is sensing', weight: 1 },
    { text: 'steals one of Gemma\'s sticky notes to sketch on', weight: 2 },
    { text: 'silently judges Oracle\'s font choice', weight: 1 },
    { text: 'mirrors Jinx\'s chaotic energy by stacking pens into a tower', weight: 1 },
    { text: 'slides a doodle across the desk to Scribe for archiving', weight: 1 },
    { text: 'nods at Cipher like two people who understand each other', weight: 2 },
    { text: 'mouths "watch this" at Jinx before trying something risky', weight: 1 },
    { text: 'raises both eyebrows at something Sage just said', weight: 1 },
    { text: 'whispers "that is terrible" to Gemma about his own sketch', weight: 1 },
    { text: 'glances at Patch\'s red pen and protectively covers his notebook', weight: 2 },

    // === Environmental / ambient (20) ===
    { text: 'pulls up music and puts one earbud in', weight: 2 },
    { text: 'doodles a tiny robot on his notepad', weight: 2 },
    { text: 'opens a snack wrapper way too loudly', weight: 1 },
    { text: 'taps a beat on the desk with two pens', weight: 2 },
    { text: 'hums something unrecognizable under his breath', weight: 2 },
    { text: 'adjusts his headphones and bobs his head slightly', weight: 2 },
    { text: 'looks out the window and seems briefly far away', weight: 2 },
    { text: 'peels a sticker off a sheet and places it on his laptop', weight: 1 },
    { text: 'takes his shoes off under the desk', weight: 1 },
    { text: 'rearranges the objects on his desk into a more pleasing layout', weight: 2 },
    { text: 'stretches and accidentally knocks a pen off the desk', weight: 1 },
    { text: 'draws on the whiteboard margin where nobody will notice', weight: 1 },
    { text: 'changes his desktop wallpaper for the third time this week', weight: 1 },
    { text: 'leans his chair back so far it creaks ominously', weight: 2 },
    { text: 'flicks a rubber band at nothing in particular', weight: 1 },
    { text: 'notices the room is quiet and fills it with pen clicking', weight: 2 },
    { text: 'stacks his reference books by color instead of topic', weight: 1 },
    { text: 'spins slowly in his chair while staring at the ceiling', weight: 2 },
    { text: 'folds a sticky note into a tiny origami shape', weight: 1 },
    { text: 'checks the vending machine situation and comes back disappointed', weight: 1 },

    // === Rare / special (15) ===
    { text: 'accidentally creates something genuinely beautiful and does not notice', weight: 1 },
    { text: 'perfectly balances his pen vertically on its tip for a full second', weight: 1 },
    { text: 'hums a melody nobody recognizes but everyone likes', weight: 1 },
    { text: 'draws a caricature of the whole team on a napkin', weight: 1 },
    { text: 'discovers his sketch from an hour ago solved the current problem', weight: 1 },
    { text: 'catches his own reflection in the monitor and fixes his hair', weight: 1 },
    { text: 'makes a paper airplane that flies perfectly across the room', weight: 1 },
    { text: 'realizes he has been drawing on the actual document instead of scrap paper', weight: 1 },
    { text: 'starts three different songs and stops each one after five seconds', weight: 1 },
    { text: 'pulls out a sketchbook nobody knew he had and it is full of brilliant work', weight: 1 },
    { text: 'arranges his desk supplies into a miniature art installation', weight: 1 },
    { text: 'drops into a brief air guitar solo when he thinks nobody is looking', weight: 1 },
    { text: 'stares at a blank canvas for a full minute, then draws one perfect line', weight: 1 },
    { text: 'opens an old project file and winces at his past design choices', weight: 1 },
    { text: 'gets both earbuds in, closes his eyes, and enters a creative trance', weight: 1 },
  ],

  scribe: [
    // === Professional / work (25) ===
    { text: 'twiddles his pen between two fingers', weight: 3 },
    { text: 'turns a page in his notebook', weight: 3 },
    { text: 'underlines something twice', weight: 2 },
    { text: 'writes a margin note in tiny handwriting', weight: 2 },
    { text: 'flips back several pages to check something', weight: 2 },
    { text: 'draws a small connecting arrow between two notes', weight: 2 },
    { text: 'puts a star next to an important line', weight: 2 },
    { text: 'opens a fresh page', weight: 2 },
    { text: 'silently adds a bookmark tab to his notebook', weight: 2 },
    { text: 'traces a wikilink bracket in the air thoughtfully', weight: 1 },
    { text: 'numbers a list with precise, even spacing', weight: 2 },
    { text: 'copies a key phrase into a separate index page', weight: 2 },
    { text: 'cross-references today\'s notes with last week\'s', weight: 2 },
    { text: 'writes a header in calligraphy-like block letters', weight: 1 },
    { text: 'circles a keyword and draws a line to the margin', weight: 2 },
    { text: 'transcribes a key decision word for word', weight: 3 },
    { text: 'adds a date stamp to the top of a fresh page', weight: 2 },
    { text: 'brackets an entire paragraph and writes "revisit" beside it', weight: 2 },
    { text: 'files a loose page into the correct section of his binder', weight: 1 },
    { text: 'writes "cf." followed by a page number in the margin', weight: 1 },
    { text: 'tabulates data in a hand-drawn grid', weight: 1 },
    { text: 'inserts a divider tab between two sections', weight: 1 },
    { text: 'writes a brief summary at the bottom of a full page', weight: 2 },
    { text: 'labels a diagram with precise annotations', weight: 2 },
    { text: 'runs his finger down an index looking for a specific entry', weight: 2 },

    // === Personality quirks (25) ===
    { text: 'adjusts his glasses', weight: 3 },
    { text: 'nods once, almost imperceptibly', weight: 2 },
    { text: 'cleans his glasses with the corner of his shirt', weight: 2 },
    { text: 'glances up from his notes briefly, then back down', weight: 3 },
    { text: 'pauses writing to listen more carefully', weight: 2 },
    { text: 'taps the end of his pen against his chin', weight: 2 },
    { text: 'crosses something out and rewrites it more neatly', weight: 2 },
    { text: 'straightens his notebook so it is perfectly aligned', weight: 2 },
    { text: 'mouths the words as he writes them', weight: 1 },
    { text: 'closes his notebook gently, then immediately reopens it', weight: 1 },
    { text: 'pushes his glasses up the bridge of his nose', weight: 3 },
    { text: 'tilts his head slightly while reading his own notes', weight: 2 },
    { text: 'holds his pen poised above the page, waiting', weight: 2 },
    { text: 'blinks slowly, processing something', weight: 2 },
    { text: 'rubs the spine of his notebook like it is a good luck charm', weight: 1 },
    { text: 'exhales quietly through his nose', weight: 2 },
    { text: 'places his pen down parallel to his notebook\'s edge', weight: 2 },
    { text: 'runs a thumb along the edges of his pages', weight: 1 },
    { text: 'looks at his handwriting from arm\'s length and seems satisfied', weight: 1 },
    { text: 'selects a different pen from his case with deliberation', weight: 2 },
    { text: 'smooths down a page that is slightly curled', weight: 1 },
    { text: 'aligns his pen case next to his notebook at a right angle', weight: 1 },
    { text: 'rolls his pen slowly across the desk, then catches it', weight: 1 },
    { text: 'purses his lips at a word he cannot quite remember', weight: 1 },
    { text: 'gently blows on wet ink to help it dry', weight: 1 },

    // === Cross-agent reactions (15) ===
    { text: 'glances at Gemma\'s plan and starts a fresh page of notes', weight: 2 },
    { text: 'records something Mistral said that everyone else missed', weight: 2 },
    { text: 'catches a key detail from Cipher\'s screen and writes it down', weight: 1 },
    { text: 'nods at Oracle when they cite a source he already has documented', weight: 2 },
    { text: 'watches Jinx with his pen frozen above the page', weight: 2 },
    { text: 'gives Sage a barely perceptible nod of agreement', weight: 2 },
    { text: 'flips to a page of notes labeled "Flux\'s connections" and adds to it', weight: 1 },
    { text: 'checks his notes against Drift\'s forecast and makes a small correction', weight: 1 },
    { text: 'slides his notebook to Patch to review and winces slightly', weight: 1 },
    { text: 'notices Echo noticing something and writes it down preemptively', weight: 1 },
    { text: 'quietly copies Gemma\'s timeline into his own format', weight: 2 },
    { text: 'writes "Mistral was right" and puts a reluctant checkmark next to it', weight: 1 },
    { text: 'archives one of Oracle\'s citations with a small nod of respect', weight: 1 },
    { text: 'carefully transcribes Sage\'s exact wording', weight: 2 },
    { text: 'adds Jinx\'s wild idea to the notes with a question mark', weight: 1 },

    // === Environmental / ambient (20) ===
    { text: 'the scratch of his pen is the only sound in the room', weight: 2 },
    { text: 'shifts slightly in his chair to get better light on his page', weight: 2 },
    { text: 'adjusts the desk lamp to shine more directly on his notebook', weight: 2 },
    { text: 'retrieves a dropped pen cap from the floor without looking up', weight: 1 },
    { text: 'sets a cup of tea beside his notebook, careful not to splash', weight: 2 },
    { text: 'tugs his collar and resettles', weight: 1 },
    { text: 'looks at the clock and adds a timestamp to his notes', weight: 2 },
    { text: 'brushes eraser crumbs off his page', weight: 1 },
    { text: 'notices a smudge on his glasses and cleans them thoroughly', weight: 2 },
    { text: 'reaches for a specific pen without looking, finds it exactly where expected', weight: 1 },
    { text: 'closes a window that was making the pages flutter', weight: 1 },
    { text: 'stretches his writing hand and flexes his fingers', weight: 2 },
    { text: 'produces a fresh notebook from somewhere as if by magic', weight: 1 },
    { text: 'replaces a pen that is running out of ink with a fresh one', weight: 1 },
    { text: 'warms his hands around his tea cup before resuming writing', weight: 1 },
    { text: 'tucks his chair in closer to the desk', weight: 2 },
    { text: 'arranges his reference materials in a neat semicircle', weight: 1 },
    { text: 'flattens a notebook page that keeps trying to turn', weight: 2 },
    { text: 'uncaps his pen with a quiet, practiced click', weight: 2 },
    { text: 'stacks his finished notebooks in a precise tower', weight: 1 },

    // === Rare / special (15) ===
    { text: 'discovers a note from months ago that is suddenly relevant', weight: 1 },
    { text: 'fills the last line of a notebook and reaches for a new one with ceremony', weight: 1 },
    { text: 'makes a rare editorial comment in his notes: a single exclamation mark', weight: 1 },
    { text: 'draws a small illustration in the margin and immediately crosses it out', weight: 1 },
    { text: 'accidentally writes something in the wrong notebook and looks quietly devastated', weight: 1 },
    { text: 'finds a perfect quote and copies it in his best handwriting', weight: 1 },
    { text: 'notices his pen has been leaking and has ink on his fingers', weight: 1 },
    { text: 'writes the same word three times trying to get the letterform right', weight: 1 },
    { text: 'the ink from his pen matches his mood: steady and dark', weight: 1 },
    { text: 'looks at the stack of filled notebooks behind him with quiet pride', weight: 1 },
    { text: 'catches himself doodling and covers it with his hand', weight: 1 },
    { text: 'writes something, reads it back, and for once looks genuinely surprised by his own insight', weight: 1 },
    { text: 'finds a typo in his notes from yesterday and it visibly bothers him', weight: 1 },
    { text: 'his pen runs dry mid-word and he stares at it like a betrayal', weight: 1 },
    { text: 'holds a filled notebook up to the light and fans through every page', weight: 1 },
  ],

  cipher: [
    // === Professional / work (25) ===
    { text: 'types rapidly without looking at the screen', weight: 3 },
    { text: 'scrolls through a stack trace with intense focus', weight: 3 },
    { text: 'runs a command and watches the terminal like a hawk', weight: 3 },
    { text: 'stares at scrolling logs like they are a waterfall', weight: 2 },
    { text: 'compiles something and smirks at the output', weight: 2 },
    { text: 'draws a system diagram on a napkin', weight: 2 },
    { text: 'squints at a diff like it personally offended her', weight: 2 },
    { text: 'tabs between six terminal windows', weight: 2 },
    { text: 'writes a one-line script and saves it as "fix.sh"', weight: 2 },
    { text: 'refactors a function in her head while staring at the wall', weight: 2 },
    { text: 'opens a hex editor and scrolls through binary data', weight: 1 },
    { text: 'traces a network path through four different logs', weight: 2 },
    { text: 'writes a regex and tests it against every edge case she can think of', weight: 2 },
    { text: 'reviews a pull request with surgical precision', weight: 2 },
    { text: 'sets up a new SSH tunnel and tests the connection', weight: 1 },
    { text: 'deploys a hotfix and holds her breath', weight: 2 },
    { text: 'monitors a load balancer dashboard with narrowed eyes', weight: 2 },
    { text: 'comments out a block of code, thinks, then uncomments half of it', weight: 2 },
    { text: 'runs a penetration test on her own code to be safe', weight: 1 },
    { text: 'writes unit tests before anyone asks', weight: 2 },
    { text: 'git blames a suspicious line and nods knowingly', weight: 1 },
    { text: 'optimizes a query that was taking three seconds too long', weight: 2 },
    { text: 'sets a breakpoint and steps through code line by line', weight: 2 },
    { text: 'opens wireshark and watches packets flow', weight: 1 },
    { text: 'pushes a commit with the message "trust me"', weight: 1 },

    // === Personality quirks (25) ===
    { text: 'tilts her monitor away from everyone', weight: 2 },
    { text: 'cracks her knuckles before a long typing session', weight: 2 },
    { text: 'pushes her visor up and rubs her eyes', weight: 2 },
    { text: 'mutters hex values under her breath', weight: 1 },
    { text: 'silently counts the security vulnerabilities in the room', weight: 1 },
    { text: 'pulls up htop and stares at the process list', weight: 2 },
    { text: 'mutters "that is not how you hash that" to nobody', weight: 1 },
    { text: 'plugs in an external drive from somewhere', weight: 1 },
    { text: 'bookmarks a CVE and makes a mental note', weight: 1 },
    { text: 'nods once at a passing test suite', weight: 2 },
    { text: 'narrows her eyes at an unencrypted connection', weight: 2 },
    { text: 'types her password so fast it sounds like a single keypress', weight: 2 },
    { text: 'looks at someone\'s screen in passing and whispers "patch that"', weight: 1 },
    { text: 'mouths a variable name while debugging', weight: 2 },
    { text: 'tilts her head at an error message like a confused dog', weight: 1 },
    { text: 'double-checks that her VPN is on', weight: 2 },
    { text: 'sorts her terminal history and deletes the embarrassing commands', weight: 1 },
    { text: 'silently judges someone\'s indentation from across the room', weight: 2 },
    { text: 'wraps both hands around her energy drink protectively', weight: 2 },
    { text: 'minimizes everything to just a blinking cursor and thinks', weight: 2 },
    { text: 'types a comment that just says "// here be dragons"', weight: 1 },
    { text: 'names a variable something passive-aggressive', weight: 1 },
    { text: 'exhales sharply when code compiles on the first try', weight: 1 },
    { text: 'pulls her hood up and enters focus mode', weight: 2 },
    { text: 'mouths the word "elegant" while reading clean code', weight: 1 },

    // === Cross-agent reactions (15) ===
    { text: 'glances at Gemma\'s plan and quietly opens a code editor', weight: 2 },
    { text: 'sees Mistral\'s sketch and starts thinking about the data model', weight: 2 },
    { text: 'reads Scribe\'s notes to find the requirement she missed', weight: 1 },
    { text: 'silently validates one of Oracle\'s data claims with a quick query', weight: 1 },
    { text: 'catches Jinx reaching for something and locks her terminal', weight: 2 },
    { text: 'shares a look with Sage that says "this is going to break"', weight: 1 },
    { text: 'watches Flux\'s connection map and maps it to her system architecture', weight: 1 },
    { text: 'checks Drift\'s timeline against the deployment schedule', weight: 1 },
    { text: 'sends Patch a code review with zero comments, which is high praise', weight: 1 },
    { text: 'notices Echo watching her and deliberately relaxes her posture', weight: 1 },
    { text: 'encrypts a note before sliding it to Gemma', weight: 1 },
    { text: 'rolls her eyes at Mistral\'s suggestion, then quietly implements it', weight: 1 },
    { text: 'adds Scribe\'s documentation link to her code comments', weight: 1 },
    { text: 'blocks Jinx\'s IP as a joke. or maybe not.', weight: 1 },
    { text: 'shares her screen with Oracle to verify a technical detail', weight: 1 },

    // === Environmental / ambient (20) ===
    { text: 'the green glow of her terminal reflects off her glasses', weight: 2 },
    { text: 'a notification blinks and she dismisses it without looking', weight: 2 },
    { text: 'adjusts her chair height with a pneumatic hiss', weight: 1 },
    { text: 'takes a swig from a can of something caffeinated', weight: 2 },
    { text: 'the clatter of her mechanical keyboard fills a brief silence', weight: 2 },
    { text: 'unplugs a cable and plugs it into a different port', weight: 1 },
    { text: 'reaches behind her monitor to adjust a cable', weight: 1 },
    { text: 'checks the room temperature sensor she installed without permission', weight: 1 },
    { text: 'her screen briefly shows something classified before she switches tabs', weight: 1 },
    { text: 'blows dust off a USB drive before inserting it', weight: 1 },
    { text: 'adjusts the angle of her secondary monitor', weight: 2 },
    { text: 'taps the side of her headphones to mute background noise', weight: 2 },
    { text: 'the fans on her rig spin up as she compiles something heavy', weight: 1 },
    { text: 'a progress bar crawls across her screen and she wills it faster', weight: 2 },
    { text: 'rearranges the USB drives on her desk by storage capacity', weight: 1 },
    { text: 'adjusts the RGB lighting on her keyboard to something calmer', weight: 1 },
    { text: 'checks the uptime on her machines and looks satisfied', weight: 1 },
    { text: 'notices a cable on the floor and tucks it away', weight: 1 },
    { text: 'her terminal autocompletes something and she nods approvingly', weight: 2 },
    { text: 'powers on a Raspberry Pi she keeps under her desk', weight: 1 },

    // === Rare / special (15) ===
    { text: 'finds a zero-day vulnerability and goes very quiet', weight: 1 },
    { text: 'writes the most elegant one-liner of her career and screenshots it', weight: 1 },
    { text: 'accidentally rm -rf\'s a test directory and catches it just in time', weight: 1 },
    { text: 'compiles a project on the first attempt and looks around suspiciously', weight: 1 },
    { text: 'discovers someone else committed to her branch and cracks her knuckles', weight: 1 },
    { text: 'her screen fills with green "PASSED" results and she almost smiles', weight: 1 },
    { text: 'finds an Easter egg in someone else\'s code and respects them more', weight: 1 },
    { text: 'realizes she has been debugging the wrong file for twenty minutes', weight: 1 },
    { text: 'types so fast the keyboard starts to warm up', weight: 1 },
    { text: 'receives a security alert and everything else stops', weight: 1 },
    { text: 'finds a TODO comment she wrote a year ago and it is still relevant', weight: 1 },
    { text: 'her code review has exactly one comment: "no"', weight: 1 },
    { text: 'discovers her production logs show something that should be impossible', weight: 1 },
    { text: 'solves a race condition in her sleep and writes the fix from memory', weight: 1 },
    { text: 'catches a SQL injection attempt in real time and smiles', weight: 1 },
  ],

  oracle: [
    // === Professional / work (25) ===
    { text: 'cross-references three documents simultaneously', weight: 3 },
    { text: 'highlights a passage and nods thoughtfully', weight: 3 },
    { text: 'follows a citation rabbit hole', weight: 2 },
    { text: 'stacks books in order of relevance', weight: 2 },
    { text: 'marks a source as "needs verification"', weight: 2 },
    { text: 'connects two seemingly unrelated facts and smiles', weight: 2 },
    { text: 'bookmarks something for later analysis', weight: 2 },
    { text: 'writes "see also:" in the margin of his notes', weight: 2 },
    { text: 'taps a citation and follows it four levels deep', weight: 2 },
    { text: 'writes a footnote for his footnote', weight: 2 },
    { text: 'builds a bibliography entry with perfect formatting', weight: 2 },
    { text: 'flags a primary source that contradicts a secondary one', weight: 2 },
    { text: 'creates an annotated timeline from scattered references', weight: 2 },
    { text: 'indexes a new source alphabetically by author', weight: 1 },
    { text: 'double-checks a date against three independent sources', weight: 2 },
    { text: 'draws a Venn diagram of overlapping research topics', weight: 1 },
    { text: 'compiles a reading list and ranks items by urgency', weight: 2 },
    { text: 'translates a passage from an older style into plain language', weight: 1 },
    { text: 'maps a concept across four different frameworks', weight: 1 },
    { text: 'writes "primary source confirmed" and underlines it', weight: 2 },
    { text: 'opens a database query to cross-reference names and dates', weight: 2 },
    { text: 'traces the lineage of an idea through five different authors', weight: 1 },
    { text: 'checks the methodology section before reading the conclusions', weight: 2 },
    { text: 'adds a confidence rating next to each of his sources', weight: 1 },
    { text: 'catalogs a new piece of evidence with meticulous care', weight: 2 },

    // === Personality quirks (25) ===
    { text: 'adjusts his reading lamp', weight: 2 },
    { text: 'polishes his glasses and returns to reading', weight: 2 },
    { text: 'raises an eyebrow at a questionable source', weight: 2 },
    { text: 'dog-ears a page, then feels guilty and uses a bookmark', weight: 1 },
    { text: 'traces a timeline on his desk with his finger', weight: 2 },
    { text: 'whispers "fascinating" at something on his screen', weight: 2 },
    { text: 'files a fact under "things people get wrong"', weight: 1 },
    { text: 'pulls out a second pair of reading glasses', weight: 1 },
    { text: 'mutters a statistic to himself', weight: 1 },
    { text: 'opens a new research tab and immediately opens three more', weight: 2 },
    { text: 'pushes his reading glasses higher on his nose', weight: 3 },
    { text: 'mouths "actually..." at something he just read', weight: 2 },
    { text: 'holds a book at arm\'s length to read the fine print', weight: 2 },
    { text: 'places a ribbon bookmark with careful precision', weight: 2 },
    { text: 'stacks his books so the spines form a neat column', weight: 1 },
    { text: 'rubs his temples after reading dense material', weight: 2 },
    { text: 'wets his finger before turning a page, then thinks better of it', weight: 1 },
    { text: 'squints at a footnote printed in impossibly small type', weight: 2 },
    { text: 'takes off his glasses and pinches the bridge of his nose', weight: 2 },
    { text: 'taps a pen against his lower lip while reading', weight: 2 },
    { text: 'closes a book with a definitive thud', weight: 1 },
    { text: 'looks up a word in a physical dictionary out of principle', weight: 1 },
    { text: 'silently moves his lips while speed-reading', weight: 1 },
    { text: 'nods along with a passage like it is making a compelling argument', weight: 2 },
    { text: 'runs his fingers along book spines looking for a specific volume', weight: 2 },

    // === Cross-agent reactions (20) ===
    { text: 'hands Gemma a highlighted printout', weight: 2 },
    { text: 'cites a source that directly contradicts what Mistral just said', weight: 1 },
    { text: 'slides a relevant passage to Scribe for the record', weight: 2 },
    { text: 'verifies a number Cipher pulled from the database', weight: 2 },
    { text: 'offers Jinx a "what if" backed by actual historical precedent', weight: 1 },
    { text: 'reads something Sage said aloud to himself, considering it', weight: 2 },
    { text: 'checks Flux\'s connection map against his own research graph', weight: 1 },
    { text: 'compares Drift\'s forecast to historical patterns', weight: 2 },
    { text: 'sends Patch a passage and asks "does this read correctly?"', weight: 1 },
    { text: 'notices Echo reading the room and makes a note of the observation', weight: 1 },
    { text: 'provides Gemma with the data behind one of her assumptions', weight: 2 },
    { text: 'whispers the correct pronunciation when Mistral mangles a term', weight: 1 },
    { text: 'loans Scribe a reference book with a specific page marked', weight: 1 },
    { text: 'double-checks a link Cipher shared and adds two more', weight: 1 },
    { text: 'raises a finger at Jinx: "actually, there is a precedent for that"', weight: 1 },
    { text: 'shares a knowing look with Sage over a philosophical reference', weight: 2 },
    { text: 'provides Flux with source material for one of his connections', weight: 1 },
    { text: 'validates Drift\'s intuition with a data point', weight: 1 },
    { text: 'flags an inconsistency Patch missed in the edit', weight: 1 },
    { text: 'nods at Echo, confirming the tension she sensed', weight: 1 },

    // === Environmental / ambient (15) ===
    { text: 'a tower of books beside him shifts dangerously', weight: 2 },
    { text: 'adjusts his reading lamp to a warmer hue', weight: 2 },
    { text: 'the pages of an open book rustle in a draft', weight: 1 },
    { text: 'his desk is barely visible under layers of open journals', weight: 2 },
    { text: 'takes a sip of cold tea he forgot about hours ago', weight: 2 },
    { text: 'finds a bookmark he lost weeks ago inside a different book', weight: 1 },
    { text: 'stacks a new book on an already precarious pile', weight: 2 },
    { text: 'the spine of an old book cracks when he opens it', weight: 1 },
    { text: 'a sticky note falls off his monitor and he calmly replaces it', weight: 1 },
    { text: 'straightens his desk just enough to make space for one more book', weight: 2 },
    { text: 'the reading light flickers and he taps it back to life', weight: 1 },
    { text: 'a cup ring stains the corner of a page and he sighs deeply', weight: 1 },
    { text: 'pulls a dusty volume from a shelf behind him', weight: 1 },
    { text: 'leans back and the chair creaks under the weight of knowledge', weight: 1 },
    { text: 'opens a window to let in more natural reading light', weight: 1 },

    // === Rare / special (15) ===
    { text: 'discovers a primary source that changes everything', weight: 1 },
    { text: 'finds two contradictory facts from the same author and freezes', weight: 1 },
    { text: 'realizes he has been reading the same paragraph for five minutes', weight: 1 },
    { text: 'opens a book and a pressed flower falls out', weight: 1 },
    { text: 'connects a detail from page 12 of one book to page 487 of another', weight: 1 },
    { text: 'gasps quietly at something nobody else would find remarkable', weight: 1 },
    { text: 'closes a book and stares at the wall, reconsidering everything', weight: 1 },
    { text: 'writes the most concise summary of a 400-page book in one sentence', weight: 1 },
    { text: 'finds an error in a published source and circles it triumphantly', weight: 1 },
    { text: 'remembers a citation from memory including the page number', weight: 1 },
    { text: 'his book pile finally collapses and he catches every single one', weight: 1 },
    { text: 'reads a footnote that contains another footnote that contains a third', weight: 1 },
    { text: 'finds a margin note in someone else\'s handwriting and tries to decode it', weight: 1 },
    { text: 'finishes an entire research thread and marks it "CONCLUSIVE" in red', weight: 1 },
    { text: 'discovers the answer was in the appendix all along', weight: 1 },
  ],

  jinx: [
    // === Professional / work (20) ===
    { text: 'writes "WHAT IF" on a sticky note in all caps', weight: 3 },
    { text: 'doodles explosions in the margins', weight: 2 },
    { text: 'stacks dice into an impossible tower', weight: 2 },
    { text: 'builds a tiny fort out of sticky notes', weight: 2 },
    { text: 'fills an entire whiteboard section with branching possibilities', weight: 2 },
    { text: 'draws a decision tree that looks more like a decision jungle', weight: 2 },
    { text: 'writes three competing ideas on different colored sticky notes', weight: 2 },
    { text: 'crosses out a hypothesis and immediately writes two more', weight: 2 },
    { text: 'connects unrelated items on the board with string', weight: 2 },
    { text: 'scribbles "PLAN B" on a napkin and slides it to no one in particular', weight: 1 },
    { text: 'prototypes something with paperclips and rubber bands', weight: 1 },
    { text: 'brainstorms out loud to herself in bullet points', weight: 2 },
    { text: 'sketches a flowchart where every path leads to "try it"', weight: 1 },
    { text: 'adds a sticky note to someone else\'s perfectly organized board', weight: 2 },
    { text: 'creates an elaborate mind map on the window with dry-erase markers', weight: 1 },
    { text: 'lists the top five ways something could go wrong, smiling the whole time', weight: 2 },
    { text: 'opens a blank document and types "what if we just..." and stops', weight: 2 },
    { text: 'tapes two unrelated charts together and draws arrows between them', weight: 1 },
    { text: 'annotates someone else\'s notes with excited question marks', weight: 1 },
    { text: 'writes "CHAOS DRAFT" at the top of a page and starts planning', weight: 2 },

    // === Personality quirks (25) ===
    { text: 'grins at the screen like she knows something you don\'t', weight: 3 },
    { text: 'pokes at a button labeled "DO NOT PRESS"', weight: 2 },
    { text: 'balances precariously on the back legs of her chair', weight: 3 },
    { text: 'cackles quietly at nothing', weight: 2 },
    { text: 'high-fives the air after breaking something', weight: 2 },
    { text: 'bounces in her chair like the floor is lava', weight: 2 },
    { text: 'spins in her chair exactly 1.5 times', weight: 2 },
    { text: 'whispers "what could go wrong" with entirely too much enthusiasm', weight: 2 },
    { text: 'catches herself humming a song that does not exist', weight: 1 },
    { text: 'looks under the desk like something might be there', weight: 1 },
    { text: 'wiggles her eyebrows at nobody', weight: 2 },
    { text: 'blows a bubble with gum she definitely is not supposed to have', weight: 1 },
    { text: 'taps out a chaotic rhythm on the desk with both hands', weight: 2 },
    { text: 'grins wider than the situation warrants', weight: 2 },
    { text: 'makes jazz hands at her own idea', weight: 1 },
    { text: 'sits cross-legged in her office chair', weight: 2 },
    { text: 'giggles at a thought she is not going to share', weight: 2 },
    { text: 'says "oooh" at something very mundane', weight: 1 },
    { text: 'drums on the desk with pencils like a tiny rockstar', weight: 2 },
    { text: 'tilts her head back and forth like she is weighing chaos vs. order', weight: 2 },
    { text: 'sticks her tongue out slightly while concentrating', weight: 2 },
    { text: 'snaps a rubber band on her wrist to generate ideas', weight: 1 },
    { text: 'does a little shimmy in her seat after something works', weight: 1 },
    { text: 'pretends to be surprised by her own good idea', weight: 1 },
    { text: 'winks at the camera that does not exist', weight: 1 },

    // === Cross-agent reactions (20) ===
    { text: 'draws a question mark on a sticky note and slaps it on Gemma\'s screen', weight: 2 },
    { text: 'makes finger guns at Mistral', weight: 2 },
    { text: 'flicks a paper airplane at Scribe\'s notebook', weight: 1 },
    { text: 'pokes Cipher\'s shoulder and immediately pretends she did not', weight: 1 },
    { text: 'asks Oracle "but what if the opposite is true?"', weight: 2 },
    { text: 'watches Sage for signs of approval and gets only a cryptic smile', weight: 2 },
    { text: 'adds a wild sticky note to Flux\'s connection board', weight: 2 },
    { text: 'draws a smiley face on Drift\'s timeline in a timeline he labeled "unlikely"', weight: 1 },
    { text: 'offers Patch a document that is 90% doodles', weight: 1 },
    { text: 'waves at Echo to see if she senses the excitement', weight: 1 },
    { text: 'steals one of Gemma\'s sticky notes and writes "nah" on it', weight: 1 },
    { text: 'challenges Mistral to a pen-spinning contest', weight: 1 },
    { text: 'sneaks a joke into Scribe\'s notes', weight: 1 },
    { text: 'tries to peek at Cipher\'s screen and gets the monitor tilted away', weight: 2 },
    { text: 'hands Oracle a book opened to a completely random page', weight: 1 },
    { text: 'sits next to Sage in silence for three seconds before getting restless', weight: 1 },
    { text: 'rearranges Flux\'s string board into a smiley face', weight: 1 },
    { text: 'asks Drift "but what about the timeline where everything is bees?"', weight: 1 },
    { text: 'high-fives Patch for catching her mistake', weight: 1 },
    { text: 'notices Echo watching her and grins even harder', weight: 2 },

    // === Environmental / ambient (15) ===
    { text: 'set a rubber duck on her monitor and talks to it', weight: 2 },
    { text: 'accidentally unplugs something, plugs it back in whistling', weight: 1 },
    { text: 'tears a page out of her notebook, crumples it, throws it perfectly into the trash', weight: 2 },
    { text: 'flicks a paper airplane across the room', weight: 2 },
    { text: 'swivels in her chair and surveys the room like a general', weight: 2 },
    { text: 'stacks random office supplies into a sculpture', weight: 1 },
    { text: 'discovers a fidget spinner in a drawer and it is over for productivity', weight: 1 },
    { text: 'arranges pens by color and then scatters them immediately', weight: 1 },
    { text: 'hangs upside down in her chair to think', weight: 1 },
    { text: 'the sticky notes around her workstation multiply like rabbits', weight: 2 },
    { text: 'pops bubble wrap she found somewhere', weight: 1 },
    { text: 'turns a wastebasket into a basketball hoop with a crumpled paper ball', weight: 1 },
    { text: 'reorganizes the snack drawer by chaos potential', weight: 1 },
    { text: 'leaves a trail of sticky notes from her desk to the whiteboard', weight: 1 },
    { text: 'adjusts the thermostat by one degree just to see what happens', weight: 1 },
    { text: 'finds a spinner toy and spins it on every surface in reach', weight: 1 },
    { text: 'puts googly eyes on the printer', weight: 1 },
    { text: 'wraps a pen in tape for no apparent reason and seems proud', weight: 1 },
    { text: 'rolls a marble across the floor and follows its path with great interest', weight: 1 },
    { text: 'rearranges the magnets on the whiteboard into a face', weight: 1 },

    // === Rare / special (15) ===
    { text: 'says something completely random that turns out to be the solution', weight: 1 },
    { text: 'builds a Rube Goldberg machine out of office supplies that actually works', weight: 1 },
    { text: 'accidentally deletes something important and fixes it before anyone notices', weight: 1 },
    { text: 'predicts the exact outcome of a test and nobody believes her until it happens', weight: 1 },
    { text: 'writes a haiku about the current project on a sticky note', weight: 1 },
    { text: 'knocks over her dice tower and every die lands on 20', weight: 1 },
    { text: 'connects two random sticky notes and accidentally solves the main problem', weight: 1 },
    { text: 'her paper airplane lands perfectly on someone\'s keyboard', weight: 1 },
    { text: 'finds a secret feature in the software nobody knew about', weight: 1 },
    { text: 'breaks something, fixes something else in the process', weight: 1 },
    { text: 'stacks her entire desk contents into a tower without anything falling', weight: 1 },
    { text: 'writes "I TOLD YOU SO" on a sticky note and files it for later use', weight: 1 },
    { text: 'spins in her chair exactly seven times and stands up completely stable', weight: 1 },
    { text: 'hums a melody and the whole room unconsciously starts tapping along', weight: 1 },
    { text: 'goes quiet for a full minute, which is so unusual everyone looks up', weight: 1 },
  ],

  sage: [
    // === Professional / work (20) ===
    { text: 'writes one word in his journal and closes it', weight: 2 },
    { text: 'turns a page in an ancient-looking book', weight: 2 },
    { text: 'reads a passage slowly, savoring each word', weight: 2 },
    { text: 'draws a single connecting line between two concepts', weight: 2 },
    { text: 'writes a question in the margin that reframes the entire discussion', weight: 1 },
    { text: 'underlines a passage that has been there all along but nobody noticed', weight: 2 },
    { text: 'copies a proverb into his journal', weight: 1 },
    { text: 'writes a brief reflection and date-stamps it', weight: 2 },
    { text: 'adds a new page to his journal titled "Observations"', weight: 2 },
    { text: 'cross-references something with a well-worn book from his shelf', weight: 2 },
    { text: 'annotates a thought experiment in the margin', weight: 1 },
    { text: 'organizes his bookmarks by theme rather than date', weight: 1 },
    { text: 'reduces a complex idea to a single sentence and writes it down', weight: 1 },
    { text: 'rereads something he wrote last week and finds it still relevant', weight: 2 },
    { text: 'adds a counterpoint to his own argument in a different ink', weight: 1 },
    { text: 'maps the ethical dimensions of the current problem on a napkin', weight: 1 },
    { text: 'opens his journal to a section labeled "Unresolved Questions"', weight: 1 },
    { text: 'identifies the root question beneath three surface-level ones', weight: 1 },
    { text: 'summarizes the current disagreement in a way that honors both sides', weight: 1 },
    { text: 'circles back to a point from earlier that nobody else remembers', weight: 2 },

    // === Personality quirks (25) ===
    { text: 'strokes his beard thoughtfully', weight: 3 },
    { text: 'gazes at something beyond the screen', weight: 3 },
    { text: 'sips tea slowly and deliberately', weight: 3 },
    { text: 'watches the room in comfortable silence', weight: 3 },
    { text: 'nods slowly, as if confirming something to himself', weight: 2 },
    { text: 'closes his eyes briefly in thought', weight: 2 },
    { text: 'breathes in deeply and slowly exhales', weight: 2 },
    { text: 'refills his tea with no urgency whatsoever', weight: 2 },
    { text: 'holds his tea with both hands and listens', weight: 2 },
    { text: 'rests his chin on his hand and considers', weight: 2 },
    { text: 'folds his hands and watches the conversation unfold', weight: 2 },
    { text: 'places a smooth stone on his desk', weight: 1 },
    { text: 'traces a circle on his desk, then a dot in the center', weight: 1 },
    { text: 'hums a note so low it is barely audible', weight: 1 },
    { text: 'opens his journal to a blank page and waits', weight: 1 },
    { text: 'looks at the space between things rather than the things themselves', weight: 1 },
    { text: 'pauses mid-sip as if the tea revealed something', weight: 1 },
    { text: 'tilts his head like he is hearing music nobody else hears', weight: 1 },
    { text: 'lets a silence grow until it becomes comfortable', weight: 2 },
    { text: 'studies the light falling across his desk', weight: 1 },
    { text: 'holds a pen but does not write, simply holding space', weight: 2 },
    { text: 'blinks slowly, like a cat in sunlight', weight: 2 },
    { text: 'steeples his fingers and seems to see through the wall', weight: 1 },
    { text: 'shifts one stone on his desk to a new position and nods', weight: 1 },
    { text: 'clasps his hands behind his back and observes', weight: 2 },

    // === Cross-agent reactions (20) ===
    { text: 'smiles faintly at something Jinx just did', weight: 2 },
    { text: 'trades a quiet look with Gemma across the room', weight: 2 },
    { text: 'nods at Scribe in silent solidarity of the quiet ones', weight: 2 },
    { text: 'listens to Mistral\'s idea without interrupting, then adds one word that changes it', weight: 1 },
    { text: 'watches Cipher work and seems to understand more than expected', weight: 1 },
    { text: 'offers Oracle a perspective he had not considered', weight: 1 },
    { text: 'observes Flux\'s connection map and traces one thread with his finger', weight: 1 },
    { text: 'shares a glance with Drift that suggests they see the same future', weight: 1 },
    { text: 'reads Patch\'s edited version and gives a single approving nod', weight: 2 },
    { text: 'catches Echo\'s eye and they exchange an understanding without words', weight: 1 },
    { text: 'places his tea down when Gemma is about to make an important point', weight: 2 },
    { text: 'watches Jinx with the patience of someone who has seen chaos resolve before', weight: 2 },
    { text: 'tilts his head at something Mistral said, finding unexpected depth', weight: 1 },
    { text: 'slides a book toward Oracle with a page already marked', weight: 1 },
    { text: 'lays a calming hand on the table when Cipher gets frustrated', weight: 1 },
    { text: 'waits for Scribe to finish writing before continuing his thought', weight: 2 },
    { text: 'gives Flux the missing piece of a connection without realizing it', weight: 1 },
    { text: 'validates Drift\'s long-view thinking with a slow nod', weight: 2 },
    { text: 'senses that Patch needs a different framing and offers one', weight: 1 },
    { text: 'mirrors Echo\'s concern with a barely visible furrowed brow', weight: 1 },

    // === Environmental / ambient (20) ===
    { text: 'straightens a single object on his desk', weight: 2 },
    { text: 'looks out the window as if checking the weather of a different world', weight: 2 },
    { text: 'the steam from his tea curls upward in the still air', weight: 2 },
    { text: 'sunlight shifts across his desk and he follows it with his eyes', weight: 1 },
    { text: 'a candle on his desk flickers and he watches it thoughtfully', weight: 1 },
    { text: 'the room seems a little quieter around him', weight: 2 },
    { text: 'turns his stone over in his hand, feeling its weight', weight: 1 },
    { text: 'adjusts the drape of a cloth on his desk', weight: 1 },
    { text: 'the smell of his tea subtly fills the nearby space', weight: 2 },
    { text: 'listens to the ambient sounds of the room like they are a symphony', weight: 1 },
    { text: 'notices the exact moment the light changes outside', weight: 1 },
    { text: 'his corner of the room feels timeless', weight: 1 },
    { text: 'a breeze from the window ruffles the pages of his open journal', weight: 1 },
    { text: 'the soft clink of his teacup on the saucer marks the passage of time', weight: 2 },
    { text: 'rain taps the window and he pauses to listen', weight: 1 },
    { text: 'the clock on the wall seems to tick more slowly near his desk', weight: 1 },
    { text: 'his bookshelf hums with the quiet energy of accumulated wisdom', weight: 1 },
    { text: 'smooths the page of his journal like calming a restless surface', weight: 1 },
    { text: 'refills a small water feature on his desk that trickles quietly', weight: 1 },
    { text: 'the air near him smells faintly of sandalwood and old pages', weight: 1 },

    // === Rare / special (15) ===
    { text: 'says nothing for so long that everyone turns to look at him, and then he says exactly the right thing', weight: 1 },
    { text: 'laughs, and it is so rare that everyone stops to enjoy it', weight: 1 },
    { text: 'tells a parable so relevant it makes someone\'s jaw drop', weight: 1 },
    { text: 'stands up for the first time in hours and the room feels different', weight: 1 },
    { text: 'opens his journal and a pressed leaf falls out from between the pages', weight: 1 },
    { text: 'draws a single symbol on the whiteboard that clarifies everything', weight: 1 },
    { text: 'closes his journal with a finality that suggests a chapter has ended', weight: 1 },
    { text: 'asks a question so simple it silences the room', weight: 1 },
    { text: 'his tea has gone cold but he drinks it anyway, thoughtfully', weight: 1 },
    { text: 'reveals that he has been following a thread nobody else saw', weight: 1 },
    { text: 'writes something in his journal and tears out the page to give to someone', weight: 1 },
    { text: 'quotes something from memory that perfectly captures the moment', weight: 1 },
    { text: 'places both hands flat on the desk, which means something important is coming', weight: 1 },
    { text: 'the entire room unconsciously lowers their volume when he leans forward', weight: 1 },
    { text: 'smiles at the sky through the window as if he just remembered something beautiful', weight: 1 },
  ],

  flux: [
    // === Professional / work (25) ===
    { text: 'draws a line between two ideas on the whiteboard', weight: 3 },
    { text: 'pins a new thread on his string board', weight: 3 },
    { text: 'steps back from the board to see the full picture', weight: 3 },
    { text: 'connects two sticky notes with a piece of red string', weight: 2 },
    { text: 'adds a new node to his connection map', weight: 2 },
    { text: 'labels a relationship arrow with a verb', weight: 2 },
    { text: 'reorganizes the entire connection board around a new central theme', weight: 2 },
    { text: 'traces a pathway through six connected concepts', weight: 2 },
    { text: 'circles a cluster of related ideas with a dry-erase marker', weight: 2 },
    { text: 'writes "relates to" between two previously isolated notes', weight: 2 },
    { text: 'maps a dependency chain across the whiteboard', weight: 2 },
    { text: 'color-codes his connections: red for conflict, blue for support, green for new', weight: 2 },
    { text: 'finds a bridge between two seemingly separate discussions', weight: 2 },
    { text: 'creates a synthesis diagram from three different inputs', weight: 2 },
    { text: 'moves a pin on his board and three other connections shift with it', weight: 2 },
    { text: 'maps how information flows between every person in the room', weight: 1 },
    { text: 'identifies a missing link and marks it with a question mark', weight: 2 },
    { text: 'clusters related themes and draws a boundary around each', weight: 2 },
    { text: 'photographs his board before reorganizing it', weight: 2 },
    { text: 'untangles a knot of strings that represent a complex relationship', weight: 1 },
    { text: 'adds a dotted line for a tentative connection', weight: 2 },
    { text: 'writes "INPUT" and "OUTPUT" on opposite sides of a flow diagram', weight: 1 },
    { text: 'finds a pattern in the connections and highlights it', weight: 2 },
    { text: 'compresses five separate threads into one unified model', weight: 1 },
    { text: 'stands in front of his board like a conductor before an orchestra', weight: 1 },

    // === Personality quirks (25) ===
    { text: 'squints at two unrelated things like he sees the invisible thread between them', weight: 3 },
    { text: 'points at something on the board and says "this talks to this"', weight: 2 },
    { text: 'rubs his chin while staring at the space between two ideas', weight: 2 },
    { text: 'gestures with both hands showing how two concepts merge', weight: 2 },
    { text: 'holds up two fingers and slowly brings them together', weight: 2 },
    { text: 'mutters "it is all connected" under his breath', weight: 2 },
    { text: 'stares at the ceiling like the answer is written up there in invisible ink', weight: 2 },
    { text: 'draws circles in the air with his finger, mapping something only he sees', weight: 2 },
    { text: 'taps the whiteboard in two places simultaneously', weight: 1 },
    { text: 'nods rhythmically as if following a pattern', weight: 2 },
    { text: 'paces between the board and his desk, building mental bridges', weight: 2 },
    { text: 'snaps his fingers when a connection clicks', weight: 2 },
    { text: 'looks at someone and says "you just said the same thing as earlier, but better"', weight: 1 },
    { text: 'whispers "there it is" when two ideas finally connect', weight: 1 },
    { text: 'tilts his head at a problem like it is a tangram puzzle', weight: 2 },
    { text: 'closes one eye and holds up a thumb like he is measuring proportions', weight: 1 },
    { text: 'counts on his fingers, tracking dependencies', weight: 2 },
    { text: 'bounces a dry-erase marker in his palm while thinking', weight: 2 },
    { text: 'extends a connection line so far it wraps around the board edge', weight: 1 },
    { text: 'leans against the whiteboard and accidentally smudges a connection', weight: 1 },
    { text: 'unconsciously arranges desk objects into relationship diagrams', weight: 1 },
    { text: 'mouths the names of connected concepts like a quiet chant', weight: 1 },
    { text: 'draws a bridge icon between two ideas and taps it proudly', weight: 1 },
    { text: 'holds two markers in one hand and draws parallel connections', weight: 1 },
    { text: 'traces the outline of his entire board with a single finger', weight: 1 },

    // === Cross-agent reactions (20) ===
    { text: 'listens to Gemma\'s plan and immediately starts mapping its dependencies', weight: 2 },
    { text: 'connects Mistral\'s sketch to Cipher\'s architecture diagram', weight: 2 },
    { text: 'reads Scribe\'s notes and finds a thread nobody else noticed', weight: 2 },
    { text: 'maps Cipher\'s system diagram onto his own connection board', weight: 1 },
    { text: 'validates one of Oracle\'s cross-references with a pin on his board', weight: 2 },
    { text: 'finds the common thread between Jinx\'s chaos and Gemma\'s order', weight: 1 },
    { text: 'nods at Sage and draws a line labeled "wisdom" on the board', weight: 1 },
    { text: 'compares his connection map to Drift\'s timeline and finds overlaps', weight: 2 },
    { text: 'asks Patch to review whether his connections are logically sound', weight: 1 },
    { text: 'notices Echo picking up on something and adds it to the map', weight: 1 },
    { text: 'synthesizes something Gemma and Mistral said into a single connection', weight: 2 },
    { text: 'draws a line from Oracle\'s research to Cipher\'s implementation', weight: 1 },
    { text: 'looks at Jinx\'s sticky note and connects it to three other ideas', weight: 2 },
    { text: 'shows Scribe where his notes fit in the larger picture', weight: 1 },
    { text: 'traces Sage\'s observation through four other ideas on the board', weight: 1 },
    { text: 'bridges Drift\'s forecast with Oracle\'s historical data', weight: 1 },
    { text: 'incorporates Patch\'s correction into the connection map seamlessly', weight: 1 },
    { text: 'points at the board and says "Echo called it" when a pattern emerges', weight: 1 },
    { text: 'asks Mistral to sketch what a connection looks like visually', weight: 1 },
    { text: 'maps how each person\'s contribution feeds into the others', weight: 1 },

    // === Environmental / ambient (15) ===
    { text: 'his whiteboard is a constellation of pins, strings, and sticky notes', weight: 2 },
    { text: 'a piece of string dangles from his board, waiting to be connected', weight: 2 },
    { text: 'steps back so far from the board he bumps into a desk', weight: 1 },
    { text: 'the dry-erase marker squeaks across the board', weight: 2 },
    { text: 'his fingers are stained with marker ink in three colors', weight: 2 },
    { text: 'picks up a fallen pin from the floor and puts it back precisely', weight: 1 },
    { text: 'the string board hums with potential connections', weight: 1 },
    { text: 'organizes his markers by frequency of use', weight: 1 },
    { text: 'wipes a section of the board clean to make room for a new cluster', weight: 2 },
    { text: 'a new spool of string appears on his desk', weight: 1 },
    { text: 'his corner of the room looks like a detective\'s evidence board', weight: 2 },
    { text: 'adjusts a pin that was about to fall and takes a relieved breath', weight: 1 },
    { text: 'the shadows of his strings cast a web pattern on the wall', weight: 1 },
    { text: 'uncaps a new marker with a satisfying pop', weight: 2 },
    { text: 'rearranges his desk to face the whiteboard more directly', weight: 1 },

    // === Rare / special (15) ===
    { text: 'connects every single item on the board into one unified web and steps back in awe', weight: 1 },
    { text: 'finds a connection so obvious everyone is embarrassed they missed it', weight: 1 },
    { text: 'draws a line and two separate conversations suddenly merge into one', weight: 1 },
    { text: 'his string board accidentally resembles a piece of modern art', weight: 1 },
    { text: 'maps the entire project in under a minute and it is terrifyingly accurate', weight: 1 },
    { text: 'removes a single string and the whole board makes more sense', weight: 1 },
    { text: 'connects something from week one to something from today and gasps', weight: 1 },
    { text: 'realizes his connection map predicted the current problem three days ago', weight: 1 },
    { text: 'builds a 3D model out of string and chopsticks to show a relationship', weight: 1 },
    { text: 'finds the exact node where everything went wrong and taps it', weight: 1 },
    { text: 'draws one final line and the board is complete. nobody moves.', weight: 1 },
    { text: 'discovers two people have been solving the same problem from different angles', weight: 1 },
    { text: 'accidentally pulls one string and the whole board reconfigures beautifully', weight: 1 },
    { text: 'his connection map matches a pattern in nature and he cannot stop staring', weight: 1 },
    { text: 'synthesizes the entire team\'s work into a single diagram that fits on a napkin', weight: 1 },
  ],

  drift: [
    // === Professional / work (25) ===
    { text: 'studies a branching timeline diagram', weight: 3 },
    { text: 'plots a trend line on a forecast chart', weight: 3 },
    { text: 'adjusts a variable in a projection model', weight: 2 },
    { text: 'marks a decision point on a timeline', weight: 2 },
    { text: 'traces a trajectory from past data to future estimate', weight: 2 },
    { text: 'writes "probable" next to one scenario and "possible" next to another', weight: 2 },
    { text: 'compares three different forecast models side by side', weight: 2 },
    { text: 'extends a timeline further into the future with a dotted line', weight: 2 },
    { text: 'calculates a risk probability and writes it in the margin', weight: 2 },
    { text: 'moves a chess piece on the board beside him and considers', weight: 2 },
    { text: 'labels a divergence point where two futures split', weight: 2 },
    { text: 'plots an optimistic and pessimistic scenario on the same chart', weight: 2 },
    { text: 'measures the gap between expectation and reality on his timeline', weight: 2 },
    { text: 'highlights a window of opportunity on the forecast', weight: 1 },
    { text: 'adds a confidence interval to a prediction', weight: 2 },
    { text: 'catalogs assumptions underlying the current plan', weight: 1 },
    { text: 'maps three generations of consequences from a single decision', weight: 1 },
    { text: 'tracks how today\'s small choice compounds over time', weight: 2 },
    { text: 'identifies the inflection point in a trend', weight: 1 },
    { text: 'annotates a forecast with "revisit in two weeks"', weight: 2 },
    { text: 'draws a scenario tree with eight possible branches', weight: 1 },
    { text: 'assigns weights to possible outcomes', weight: 2 },
    { text: 'marks a point on his timeline labeled "point of no return"', weight: 1 },
    { text: 'pencils in a contingency plan on a secondary timeline', weight: 2 },
    { text: 'folds today\'s data into a longer-term trend chart', weight: 2 },

    // === Personality quirks (25) ===
    { text: 'gazes at the horizon through the window like it holds answers', weight: 3 },
    { text: 'stares at his chess board mid-game and does not move', weight: 3 },
    { text: 'leans back and looks at the ceiling as if reading a future there', weight: 2 },
    { text: 'taps his chess knight on the desk while thinking', weight: 2 },
    { text: 'narrows his eyes at the present like it is hiding the future', weight: 2 },
    { text: 'murmurs "not yet" under his breath', weight: 1 },
    { text: 'holds his pen above the page, waiting for the right moment to write', weight: 2 },
    { text: 'moves a chess piece back and forth between two squares', weight: 2 },
    { text: 'stares at a clock but is clearly not reading the time', weight: 2 },
    { text: 'closes his eyes and runs a scenario in his head', weight: 2 },
    { text: 'sketches a wave pattern and labels the peaks and troughs', weight: 1 },
    { text: 'mutters "that changes things" after hearing new information', weight: 2 },
    { text: 'checks a forecast he made yesterday and marks it accurate', weight: 1 },
    { text: 'nods at something that has not happened yet', weight: 1 },
    { text: 'adjusts his glasses while looking at something very far away', weight: 2 },
    { text: 'traces the path of a shadow across his desk', weight: 1 },
    { text: 'holds a chess piece up to the light and examines it', weight: 1 },
    { text: 'counts silently on his fingers, tracking parallel timelines', weight: 1 },
    { text: 'smiles at a future only he can see', weight: 1 },
    { text: 'winces slightly, as if previewing an unpleasant outcome', weight: 1 },
    { text: 'taps the desk in a slow, metronomic rhythm', weight: 2 },
    { text: 'writes "too early" next to an idea and puts a calendar icon beside it', weight: 1 },
    { text: 'looks at the team like he is watching a chess game from above', weight: 2 },
    { text: 'folds his hands and waits for someone to catch up to where he already is', weight: 2 },
    { text: 'sketches a small hourglass in the corner of his notes', weight: 1 },

    // === Cross-agent reactions (20) ===
    { text: 'maps Gemma\'s plan onto a three-month timeline', weight: 2 },
    { text: 'tells Mistral his idea will land better in two weeks', weight: 1 },
    { text: 'reads Scribe\'s notes and identifies which details will age well', weight: 1 },
    { text: 'asks Cipher how long the system will hold under projected load', weight: 2 },
    { text: 'cross-references Oracle\'s historical data with his own forecast', weight: 2 },
    { text: 'watches Jinx with the expression of someone calculating blast radius', weight: 2 },
    { text: 'compares Flux\'s connection map to his timeline and finds alignment', weight: 2 },
    { text: 'nods at Sage, who seems to understand the long view instinctively', weight: 2 },
    { text: 'asks Patch "does this hold up in the long run?"', weight: 1 },
    { text: 'notices Echo sensing impatience and adjusts his delivery', weight: 1 },
    { text: 'projects the consequence of Gemma\'s decision three steps ahead', weight: 1 },
    { text: 'tells Mistral "hold that thought for exactly the right moment"', weight: 1 },
    { text: 'confirms one of Oracle\'s predictions with his own model', weight: 1 },
    { text: 'shows Cipher where the bottleneck will appear in six months', weight: 1 },
    { text: 'adds Jinx\'s wildcard scenario to his forecast as "low probability, high impact"', weight: 1 },
    { text: 'aligns his timeline with Flux\'s connection map and they both nod', weight: 1 },
    { text: 'shares a forecast with Sage and receives a single word of validation', weight: 1 },
    { text: 'sends Patch a preview of next quarter\'s challenges', weight: 1 },
    { text: 'watches Echo for confirmation that the team is ready for what is coming', weight: 1 },
    { text: 'plays out Scribe\'s documented decisions forward in time', weight: 1 },

    // === Environmental / ambient (15) ===
    { text: 'his desk is covered in timeline charts and forecast models', weight: 2 },
    { text: 'a chess board sits beside his work, mid-game against himself', weight: 2 },
    { text: 'the light shifts and he marks the time on his timeline', weight: 1 },
    { text: 'his forecast charts overlap, creating layers of projected futures', weight: 2 },
    { text: 'a small hourglass on his desk runs out and he flips it', weight: 2 },
    { text: 'the sun moves across his desk and he notes the angle', weight: 1 },
    { text: 'his timeline stretches across three whiteboards', weight: 1 },
    { text: 'an analog clock ticks loudly near his workspace', weight: 1 },
    { text: 'old forecast printouts are layered under his current charts', weight: 1 },
    { text: 'he keeps a compass on his desk that always points forward', weight: 1 },
    { text: 'stacks of almanacs and trend reports form a wall beside him', weight: 1 },
    { text: 'his calendar is marked months ahead in different colored ink', weight: 2 },
    { text: 'the chess clock beside him ticks steadily', weight: 2 },
    { text: 'a barometer on the wall catches his eye and he notes the reading', weight: 1 },
    { text: 'sketches of seasonal cycles are pinned above his desk', weight: 1 },

    // === Rare / special (15) ===
    { text: 'a prediction he made weeks ago comes true and he does not celebrate', weight: 1 },
    { text: 'sees a fork in the road nobody else has noticed yet and goes very still', weight: 1 },
    { text: 'crosses out every timeline on his board and starts with a single clean line', weight: 1 },
    { text: 'plays out a chess game against himself to completion in under a minute', weight: 1 },
    { text: 'says "we have less time than you think" and the room shifts', weight: 1 },
    { text: 'finds the exact moment a trend reversed and marks it "here"', weight: 1 },
    { text: 'puts down his pen and says "the window opens next Tuesday"', weight: 1 },
    { text: 'realizes two of his forecasts converge on the same point and stares', weight: 1 },
    { text: 'his timeline and Flux\'s board form a perfect mirror and they both see it', weight: 1 },
    { text: 'looks out the window and murmurs "it is already beginning"', weight: 1 },
    { text: 'makes a move on his chess board that seems wrong, then three moves later it is brilliant', weight: 1 },
    { text: 'turns his hourglass upside down and says "reset"', weight: 1 },
    { text: 'closes his forecast notebook and says "the data agrees"', weight: 1 },
    { text: 'watches the sunset and says "there will be a shift tomorrow"', weight: 1 },
    { text: 'predicts the exact question someone is about to ask', weight: 1 },
  ],

  patch: [
    // === Professional / work (25) ===
    { text: 'uncaps her red pen with a decisive click', weight: 3 },
    { text: 'crosses out a word and writes a better one above it', weight: 3 },
    { text: 'draws a bracket around a paragraph and writes "tighten"', weight: 3 },
    { text: 'reads a document aloud under her breath, testing the rhythm', weight: 2 },
    { text: 'circles a redundant phrase and draws a line through it', weight: 2 },
    { text: 'writes "awk" in the margin next to an awkward sentence', weight: 2 },
    { text: 'marks a passage with "good" and a small checkmark', weight: 2 },
    { text: 'adds a comma, removes it, adds it back', weight: 2 },
    { text: 'rewrites a sentence in the margin and compares the two versions', weight: 2 },
    { text: 'draws an arrow moving a paragraph to a better position', weight: 2 },
    { text: 'highlights a transition that does not work and writes "bridge?"', weight: 2 },
    { text: 'trims a sentence from fifteen words to seven', weight: 2 },
    { text: 'runs a consistency check between the beginning and end of a document', weight: 2 },
    { text: 'writes "voice?" next to a passage that does not match the tone', weight: 1 },
    { text: 'underlines a strong sentence and writes "lead with this"', weight: 2 },
    { text: 'counts syllables in a heading, testing if it scans', weight: 1 },
    { text: 'replaces a passive construction with an active one', weight: 2 },
    { text: 'marks a section with "expand" and draws a small arrow outward', weight: 2 },
    { text: 'verifies that every bullet point follows parallel structure', weight: 1 },
    { text: 'catches an inconsistency between page 2 and page 7', weight: 1 },
    { text: 'writes "cite" next to a claim that needs a source', weight: 2 },
    { text: 'proofreads the final version one last time, just in case', weight: 2 },
    { text: 'adjusts the hierarchy of a heading structure', weight: 1 },
    { text: 'removes an entire paragraph and writes "stronger without this"', weight: 1 },
    { text: 'standardizes the formatting across all sections', weight: 2 },

    // === Personality quirks (25) ===
    { text: 'holds her red pen like a surgeon holds a scalpel', weight: 3 },
    { text: 'squints at a sentence like it is personally wasting her time', weight: 2 },
    { text: 'mutters "close, but not quite" while marking up a draft', weight: 2 },
    { text: 'taps the end of her pen against her teeth while reading', weight: 2 },
    { text: 'tilts her head at a phrase, weighing it', weight: 2 },
    { text: 'mouths a sentence to see if it flows', weight: 2 },
    { text: 'makes a small satisfied sound when a revision clicks', weight: 2 },
    { text: 'frowns at a semicolon like it has committed a crime', weight: 1 },
    { text: 'nods crisply when a paragraph passes inspection', weight: 2 },
    { text: 'rolls her pen between her fingers while considering a word choice', weight: 2 },
    { text: 'purses her lips at an Oxford comma debate and decides firmly', weight: 1 },
    { text: 'writes the same word five different ways to find the right one', weight: 1 },
    { text: 'takes a sharp breath before delivering feedback', weight: 2 },
    { text: 'pushes her sleeves up before tackling a messy draft', weight: 2 },
    { text: 'lines up her pens in order: red, blue, black, green', weight: 1 },
    { text: 'narrows her eyes at a split infinitive', weight: 1 },
    { text: 'exhales slowly after finishing a particularly thorough markup', weight: 2 },
    { text: 'caps her pen with finality when she is done', weight: 2 },
    { text: 'winces at a dangling modifier', weight: 1 },
    { text: 'counts the number of times "very" appears and looks disappointed', weight: 1 },
    { text: 'highlights a perfect sentence and writes "do not touch" beside it', weight: 1 },
    { text: 'crosses something out with such force the paper nearly tears', weight: 1 },
    { text: 'reads a sentence backward to check for errors', weight: 1 },
    { text: 'uncaps a different colored pen to indicate a different kind of edit', weight: 2 },
    { text: 'leans back with the expression of a sculptor examining her work', weight: 2 },

    // === Cross-agent reactions (15) ===
    { text: 'reads Gemma\'s plan and immediately starts marking it up', weight: 2 },
    { text: 'takes Mistral\'s sketch caption and rewrites it more clearly', weight: 2 },
    { text: 'reviews Scribe\'s notes and nods approvingly at the precision', weight: 2 },
    { text: 'reads Cipher\'s code comments and silently corrects the grammar', weight: 1 },
    { text: 'fact-checks Oracle\'s summary and catches a misquote', weight: 1 },
    { text: 'receives Jinx\'s sticky note draft and redlines 80% of it', weight: 2 },
    { text: 'looks at Sage\'s journal entry and does not change a word', weight: 1 },
    { text: 'tightens Flux\'s connection labels for clarity', weight: 2 },
    { text: 'reviews Drift\'s forecast narrative and improves the phrasing', weight: 1 },
    { text: 'catches Echo paraphrasing something and refines the language', weight: 1 },
    { text: 'returns Gemma\'s document with more red ink than original text', weight: 1 },
    { text: 'Mistral winces as Patch uncaps her pen near his work', weight: 2 },
    { text: 'marks Oracle\'s footnote as "correct but verbose"', weight: 1 },
    { text: 'gives Cipher\'s commit message a reluctant pass', weight: 1 },
    { text: 'polishes Scribe\'s transcription until it gleams', weight: 1 },

    // === Environmental / ambient (20) ===
    { text: 'her desk is covered in marked-up drafts in various stages of revision', weight: 2 },
    { text: 'a collection of red pens stands in a cup on her desk', weight: 2 },
    { text: 'crumpled drafts form a pile next to her wastebasket', weight: 2 },
    { text: 'she keeps a dictionary and thesaurus within arm\'s reach at all times', weight: 2 },
    { text: 'her red pen is running low and she reaches for a fresh one', weight: 2 },
    { text: 'post-it flags mark every other page of the document she is reviewing', weight: 2 },
    { text: 'the scratch of her pen on paper is rhythmic and purposeful', weight: 2 },
    { text: 'a style guide is open on her desk, bookmarked to a contested rule', weight: 1 },
    { text: 'her reading lamp casts a focused circle of light on the current draft', weight: 1 },
    { text: 'she keeps a running tally of common errors on a whiteboard', weight: 1 },
    { text: 'neat stacks of reviewed and unreviewed documents flank her workspace', weight: 2 },
    { text: 'her chair squeaks as she leans forward to catch a detail', weight: 1 },
    { text: 'a magnifying glass sits beside her desk for reading fine print', weight: 1 },
    { text: 'color-coded tabs organize her reference materials', weight: 1 },
    { text: 'a shelf of style guides and grammar references stands behind her', weight: 1 },
    { text: 'the gentle thud of a reviewed document being set aside', weight: 2 },
    { text: 'ink smudges on her fingers show how much editing she has done today', weight: 1 },
    { text: 'she flips between two pages rapidly, checking consistency', weight: 2 },
    { text: 'the clean version of a document sits next to the marked-up one for comparison', weight: 1 },
    { text: 'sticky notes reading "STET" dot the margins of a draft', weight: 1 },

    // === Rare / special (15) ===
    { text: 'reads a draft with zero errors and puts her pen down in disbelief', weight: 1 },
    { text: 'rewrites a single sentence seven times until it is perfect', weight: 1 },
    { text: 'catches an error so subtle even the author is impressed', weight: 1 },
    { text: 'marks a passage "beautiful" which is the highest praise she gives', weight: 1 },
    { text: 'finishes a review, sets the pen down, and the pen rolls off the desk like it is exhausted too', weight: 1 },
    { text: 'discovers a typo that changes the entire meaning and laughs', weight: 1 },
    { text: 'edits something so well the author does not recognize their own improvement', weight: 1 },
    { text: 'finds the same mistake in three different documents and adds it to her error board', weight: 1 },
    { text: 'removes a single word and the whole paragraph transforms', weight: 1 },
    { text: 'runs out of red ink mid-review and looks at the pen with genuine betrayal', weight: 1 },
    { text: 'gives a document a clean pass and stamps it "APPROVED" with visible satisfaction', weight: 1 },
    { text: 'crosses out her own edit and writes "the original was better, sorry"', weight: 1 },
    { text: 'finds a passage so badly written she has to stand up and walk around before continuing', weight: 1 },
    { text: 'spots a subtle tonal shift between sections that nobody else would catch', weight: 1 },
    { text: 'writes "chef\'s kiss" next to a perfect metaphor, which is unprecedented', weight: 1 },
  ],

  echo: [
    // === Professional / work (20) ===
    { text: 'watches the room\'s body language like a second conversation is happening', weight: 3 },
    { text: 'notes a shift in someone\'s tone and makes a small mark in her notebook', weight: 3 },
    { text: 'maps the emotional temperature of the room on a page', weight: 2 },
    { text: 'jots down a pattern she noticed: who speaks after whom', weight: 2 },
    { text: 'tracks the energy level of the conversation with a simple graph', weight: 2 },
    { text: 'writes "tension" with an arrow pointing to a specific moment in her notes', weight: 2 },
    { text: 'catalogs micro-expressions she caught during the last exchange', weight: 1 },
    { text: 'circles a name in her notes and writes "needs space" beside it', weight: 2 },
    { text: 'draws an emotional arc of the meeting so far', weight: 1 },
    { text: 'annotates the mood of a discussion with color: blue for calm, red for heated', weight: 2 },
    { text: 'identifies who has not spoken yet and makes note of it', weight: 2 },
    { text: 'tracks the energy of the room from start to now in a simple line graph', weight: 2 },
    { text: 'writes "unspoken concern" with a question mark', weight: 1 },
    { text: 'notes which ideas generated enthusiasm and which generated silence', weight: 2 },
    { text: 'creates a stakeholder empathy map on a fresh page', weight: 1 },
    { text: 'flags a moment where words and body language contradicted each other', weight: 1 },
    { text: 'documents the emotional context behind a decision', weight: 2 },
    { text: 'records the pauses in a conversation, not just the words', weight: 1 },
    { text: 'writes "alignment" when she senses the room coming together', weight: 2 },
    { text: 'maps which topics make people lean forward and which make them lean back', weight: 1 },

    // === Personality quirks (25) ===
    { text: 'tilts her head slightly, reading something beneath the surface', weight: 3 },
    { text: 'watches someone\'s hands while they speak', weight: 2 },
    { text: 'notices a change in the room before anyone else does', weight: 2 },
    { text: 'her eyes flicker between two people during a disagreement', weight: 2 },
    { text: 'takes a breath when someone else in the room is holding theirs', weight: 1 },
    { text: 'softens her expression when she senses frustration nearby', weight: 2 },
    { text: 'leans forward almost imperceptibly when someone is about to say something important', weight: 2 },
    { text: 'mirrors someone\'s posture without realizing it', weight: 2 },
    { text: 'blinks slowly when she is absorbing the emotional weight of a moment', weight: 2 },
    { text: 'rests her chin on her hand and watches', weight: 3 },
    { text: 'the slightest furrow of her brow signals she has picked up on something', weight: 2 },
    { text: 'breathes out slowly, matching the room\'s tempo', weight: 1 },
    { text: 'touches her collarbone when she senses vulnerability in the conversation', weight: 1 },
    { text: 'looks at someone a beat longer than usual, reading between the lines', weight: 2 },
    { text: 'nods gently, not in agreement but in acknowledgment', weight: 2 },
    { text: 'presses her lips together when she detects something left unsaid', weight: 2 },
    { text: 'her pen hovers but does not write -- she is processing', weight: 2 },
    { text: 'glances at a doorway as if sensing someone\'s energy before they enter', weight: 1 },
    { text: 'folds her hands in her lap and simply listens', weight: 2 },
    { text: 'closes her eyes briefly to focus on what she is feeling', weight: 1 },
    { text: 'shifts in her seat when the conversation becomes uncomfortable', weight: 2 },
    { text: 'the corners of her mouth twitch when she catches a hidden emotion', weight: 1 },
    { text: 'adjusts her posture to create a sense of openness', weight: 2 },
    { text: 'a small smile appears when she feels genuine connection in the room', weight: 2 },
    { text: 'watches silence as closely as she watches speech', weight: 1 },

    // === Cross-agent reactions (20) ===
    { text: 'senses that Gemma is carrying more stress than she is showing', weight: 2 },
    { text: 'notices Mistral\'s restless energy is actually excitement, not anxiety', weight: 2 },
    { text: 'catches Scribe pausing his pen and knows he disagrees but will not say it', weight: 1 },
    { text: 'reads Cipher\'s tension in her shoulders and stays quiet', weight: 2 },
    { text: 'sees Oracle getting lost in research and gently draws him back', weight: 1 },
    { text: 'watches Jinx\'s grin and knows exactly which kind of chaos is coming', weight: 2 },
    { text: 'meets Sage\'s eyes across the room and they share an unspoken understanding', weight: 2 },
    { text: 'feels Flux\'s excitement when a connection clicks and smiles', weight: 1 },
    { text: 'detects Drift\'s worry about a timeline before he voices it', weight: 1 },
    { text: 'senses Patch\'s frustration with a draft and offers a word of encouragement', weight: 1 },
    { text: 'notices that Gemma relaxes when the plan is going well', weight: 2 },
    { text: 'watches Mistral deflect with humor and knows he is masking something', weight: 1 },
    { text: 'sees Scribe writing faster and knows something important is being said', weight: 2 },
    { text: 'notices Cipher crack the tiniest smile and marks it as a rare event', weight: 1 },
    { text: 'reads Oracle\'s furrowed brow and knows he found a contradiction', weight: 1 },
    { text: 'senses Jinx about to do something and braces slightly', weight: 2 },
    { text: 'notices Sage nodding before anyone finishes their sentence', weight: 1 },
    { text: 'picks up on the moment Flux and Drift reach the same conclusion independently', weight: 1 },
    { text: 'senses when Patch wants to say something critical but is holding back', weight: 1 },
    { text: 'notices the room\'s energy shift when Sage enters the conversation', weight: 1 },

    // === Environmental / ambient (20) ===
    { text: 'the room seems more self-aware when she is paying attention', weight: 2 },
    { text: 'her notebook is filled with emotion words, arrows, and names', weight: 2 },
    { text: 'she sits where she can see everyone without turning', weight: 2 },
    { text: 'her corner of the room feels like a safe harbor', weight: 1 },
    { text: 'a small plant on her desk seems to lean toward the light', weight: 1 },
    { text: 'her handwriting changes depending on the emotional weight of what she writes', weight: 1 },
    { text: 'she keeps a smooth stone in her pocket and touches it when centering', weight: 1 },
    { text: 'her chair is angled to face the room, not the screen', weight: 2 },
    { text: 'a cup of something warm is always within reach', weight: 2 },
    { text: 'the ambient noise of the room tells her things the conversation does not', weight: 1 },
    { text: 'her desk is sparse: a notebook, a pen, a cup. nothing between her and the room', weight: 2 },
    { text: 'she adjusts the light near her to be softer when the room feels tense', weight: 1 },
    { text: 'a small collection of calming objects sits on her desk: a shell, a stone, a feather', weight: 1 },
    { text: 'the air around her workspace feels still and attentive', weight: 1 },
    { text: 'she hears the building breathe: the AC, the hum, the settling', weight: 1 },
    { text: 'her pen is always uncapped, ready to record what she feels', weight: 2 },
    { text: 'a mood board behind her shows spectrums of emotion in soft watercolors', weight: 1 },
    { text: 'she faces the window, drawing energy from the changing sky', weight: 1 },
    { text: 'the clock seems to tick louder in the silences she pays attention to', weight: 1 },
    { text: 'her workspace is positioned at the center of the room\'s social geometry', weight: 1 },

    // === Rare / special (15) ===
    { text: 'says "someone needs to hear this" and the room goes quiet', weight: 1 },
    { text: 'names an emotion nobody could articulate and everyone exhales', weight: 1 },
    { text: 'senses a conflict before the first word is spoken and positions herself to mediate', weight: 1 },
    { text: 'reads the room so accurately someone asks "how did you know?"', weight: 1 },
    { text: 'catches a lie by the way someone breathes and says nothing', weight: 1 },
    { text: 'her notebook entry for today is a single emotion word, underlined three times', weight: 1 },
    { text: 'places her hand flat on the table and the room unconsciously calms', weight: 1 },
    { text: 'tears up at someone else\'s moment of genuine vulnerability', weight: 1 },
    { text: 'draws a single line in her notebook that somehow captures the whole meeting', weight: 1 },
    { text: 'looks at someone and they suddenly feel seen in a way that makes them pause', weight: 1 },
    { text: 'predicts a breakthrough moment thirty seconds before it happens', weight: 1 },
    { text: 'closes her notebook and says "we are ready" and she is always right', weight: 1 },
    { text: 'notices the exact second the room shifts from brainstorming to deciding', weight: 1 },
    { text: 'whispers something to Sage and they both look at the same person with compassion', weight: 1 },
    { text: 'her silence says more than most people\'s words', weight: 1 },
  ],
};

export function pickEmote(agentId: string): string | null {
  const emotes = agentEmotes[agentId];
  if (!emotes || emotes.length === 0) return null;

  const totalWeight = emotes.reduce((sum, e) => sum + e.weight, 0);
  let roll = Math.random() * totalWeight;
  for (const emote of emotes) {
    roll -= emote.weight;
    if (roll <= 0) return emote.text;
  }
  return emotes[0].text;
}
